apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbide-dns-deployment
  labels:
    app: carbide-dns
spec:
  selector:
    matchLabels:
      app: carbide-dns
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: carbide-dns
    spec:
      containers:
        - name: carbide-dns
          image: carbide:latest
          command: ["/bin/sh", "-c", "/opt/carbide/carbide-dns run --carbide-url=\"${CARBIDE_API}\""]
          envFrom:
          - configMapRef:
              name: carbide-dns-configuration
          imagePullPolicy:  IfNotPresent
          ports:
            - containerPort: 1053
