apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: carbide-dns
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: carbide-dns-configuration
    behavior:  create
    literals:
      - "CARBIDE_API=http://carbide-api:1079"
