apiVersion: v1
kind: Service
metadata:
  name: carbide-dns
spec:
  ports:
  - port: 1053
    name: carbide-dns-udp
    protocol: UDP
  - port: 1053
    name: carbide-dns-tcp
    protocol: TCP
  selector:
    app: carbide-dns
