[package]
name = "carbide-mlxconfig-embedded"
version = "0.0.0"
edition = "2021"
description = "Example CLI tool for working with the mlxconfig_registry/variables crates."

[lib]
name = "mlxconfig_embedded"

[[bin]]
name = "mlxconfig-embedded"
path = "src/main.rs"

[dependencies]
serde = { features = ["derive"] , workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
regex = { workspace = true }
clap = { features = ["derive"] , workspace = true }
prettytable-rs = { workspace = true }
carbide-mlxconfig-device = { path = "../../common/mlxconfig/device" }
carbide-mlxconfig-lockdown = { path = "../../common/mlxconfig/lockdown" }
carbide-mlxconfig-profile = { path = "../../common/mlxconfig/profile" }
carbide-mlxconfig-registry = { path = "../../common/mlxconfig/registry" }
carbide-mlxconfig-runner = { path = "../../common/mlxconfig/runner" }
carbide-mlxconfig-variables = { path = "../../common/mlxconfig/variables" }
