[package]
name = "systest"
edition.workspace = true
version = "0.1.0"
authors = ["Vishnu Rangayyan <vrangayyan@nvidia.com>"]

[dependencies]
freeipmi-sys = { path = "..", default-features = false, features = ["libc"] }
getopts = "0.2.21"
libc = { version = "0.2", optional = true }

[build-dependencies]

[features]
default = ["libc"]
