[package]
name = "carbide-pxe"
version = "0.0.1"
edition = "2018"
description = "Carbide is a Bare Metal Provisioning system with auto-discovery and API based machine manipulation"
#readme = "README.md"

[[bin]]
name = "carbide"
path = "src/main.rs"

[dependencies]
# protobufs/rpc interface
rpc = { path = "../rpc" }
tonic = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"

# webserver
rocket = { version = "0.5.0-rc.1", features = ["uuid"] }
tera = "*"

# data types
uuid = { version = "0.8", features = ["v4", "serde"] }
ip_network = { version = "0.4.0", features = ["postgres", "serde"] }
eui48 = "0.4.0"

# misc
itertools = "*"
thiserror = "1.0"
clap = "3.0.0"
clap_derive = "3.0.0"

[build-dependencies]
tonic-build = "*"

[dev-dependencies]
rand = "*"
rstest = "*"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["tera"]

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "../vendor"
