[package]
name = "carbide-pxe"
version = "0.0.1"
edition = "2018"
description = "Carbide is a Bare Metal Provisioning system with auto-discovery and API based machine manipulation"
#readme = "README.md"

[[bin]]
name = "carbide"
path = "src/main.rs"

[dependencies]
# protobufs/rpc interface
rpc = { path = "../rpc" }
tonic = "0.7.0"
serde = { version = "*", features = ["derive"] }
serde_json = "*"

# webserver
rocket = { version = "= 0.5.0-rc.1", features = ["uuid"] }
tera = "*"

# data types
uuid = { version = "0.8.2", features = ["v4", "serde"] }
ip_network = { version = "0.4.0", features = ["postgres", "serde"] }
eui48 = "0.4.0"

# misc
itertools = "*"
thiserror = "1.0"

# cli
clap = { version = "~3", features = ["derive"]}

[build-dependencies]
tonic-build = "0.7.0"

[dev-dependencies]
rand = "*"
rstest = "*"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["tera"]

[dependencies.rocket_codegen]
version = "= 0.5.0-rc.1"

[dependencies.rocket_http]
version = "= 0.5.0-rc.1"
