[package]
name = "carbide-pxe"
version = "0.0.1"
edition.workspace = true
license = "LicenseRef-NvidiaProprietary"
description = "Carbide is a Bare Metal Provisioning system with auto-discovery and API based machine manipulation"
authors = ["NVIDIA Forge Engineering <swngc-forge-dev@exchange.nvidia.com>"]

[[bin]]
name = "carbide"
path = "src/main.rs"

[dependencies]
base64 = "0.21.5"
clap = { workspace = true }
eui48 = { version = "1", default-features = false } # disable feature rustc-serialize
forge-version = { path = "../version" }
ip_network = { version = "0.4.0", features = ["postgres", "serde"] }
itertools = "*"
rocket = { version = "= 0.5.0-rc.1", features = ["uuid"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tera = "*"
thiserror = "1.0"
tokio = { workspace = true }
tonic = { workspace = true }
uuid = { version = "1.0", features = ["v4", "serde"] }

rpc = { path = "../rpc" }

[build-dependencies]
tonic-build = "0.8.0"
forge-version = { path = "../version" }

[dev-dependencies]
toml = "0.8.8"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["tera"]

[dependencies.rocket_codegen]
version = "= 0.5.0-rc.1"

[dependencies.rocket_http]
version = "= 0.5.0-rc.1"
