[package]
name = "carbide-pxe"
version = "0.0.1"
edition.workspace = true
license = "LicenseRef-NvidiaProprietary"
description = "Carbide is a Bare Metal Provisioning system with auto-discovery and API based machine manipulation"
authors = ["NVIDIA Forge Engineering <swngc-forge-dev@exchange.nvidia.com>"]

[[bin]]
name = "carbide"
path = "src/main.rs"

[dependencies]
async-compression = { version = "0.3.14", features = ["tokio", "gzip"] }
base64 = "0.13"
clap = { version = "~3", features = ["derive"]}
eui48 = "0.4.0"
futures = "0.3.24"
futures-util = "0.3.24"
hex = "0.4.3"
ip_network = { version = "0.4.0", features = ["postgres", "serde"] }
itertools = "*"
rand = "0.8"
reqwest = { version = "0.11.11", features = ["stream"] }
rocket = { version = "= 0.5.0-rc.1", features = ["uuid"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
sha2 = "0.10.3"
tera = "*"
thiserror = "1.0"
tokio = { workspace = true }
tokio-tar = "0.3.0"
tonic = "0.8.0"
uuid = { version = "1.0", features = ["v4", "serde"] }

rpc = { path = "../rpc" }

[build-dependencies]
tonic-build = "0.8.0"

[dev-dependencies]
rand = "*"
rstest = "*"
toml = "0.5.10"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["tera"]

[dependencies.rocket_codegen]
version = "= 0.5.0-rc.1"

[dependencies.rocket_http]
version = "= 0.5.0-rc.1"
