[default]
address = "0.0.0.0"
carbide_api_internal_url = "https://carbide-api:1079"
carbide_api_url = "https://carbide-api:1079"
carbide_pxe_url = "http://172.20.0.18:8080"
carbide_ntp_server = "0.0.0.0"
port = 8000

[development]
template_dir = "templates"

[production]
template_dir = "pxe/templates"
