[package]
name = "bmc-mock"
version = "0.1.0"
description = "HTTP server that pretends to be a BMC / libredfish. For integration and local testing."
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[dependencies]
axum = { workspace = true }
axum-server = { version = "0.7", features = ["tls-rustls"] }
libredfish = { workspace = true }
clap = { workspace = true }
tokio.workspace = true
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.91"
thiserror = "2"
tar = "0.4.40"
eyre = "0.6.12"
flate2 = "1.0.30"
tower = "0.5.1"
hyper = { workspace = true }
http-body = "1.0.0"
regex = "1.10.5"
lazy_static = "1.5.0"
mac_address = { version = "1", features = ["serde"] }
chrono = "0.4"
tower-http = { version = "0.6", features = ["normalize-path"] }
bytes = { version = "1" }
form_urlencoded = "1"
itertools = "0.14"
futures = "0.3"
rand = "0.9"
rustls = { workspace = true, features = ["default", "ring"] }
rustls-pemfile = "2.2.0"
http-body-util = "0.1.2"

[lints]
workspace = true