[package]
name = "bmc-mock"
version = "0.1.0"
description = "HTTP server that pretends to be a BMC / libredfish. For integration and local testing."
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[dependencies]
axum = "0.7.5"
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
libredfish = { workspace = true }
clap = { workspace = true }
tokio.workspace = true
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.91"
thiserror = "1"
tar = "0.4.40"
eyre = "0.6.12"
flate2 = "1.0.30"
tower = "0.4.13"
hyper = { version = "1.4.0", features = ["server", "http2"] }
http-body = "1.0.0"