apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  labels:
    app: postgres
data:
  POSTGRES_DB: carbide_development
  POSTGRES_USER: carbide_development
  POSTGRES_PASSWORD: notforprod