---
apiVersion: resource.vpc.forge.gitlab-master.nvidia.com/v1alpha1
kind: ManagedResource
metadata:
  name: test-managedresource-dpu-1
  namespace: forge-system
spec:
  resourceGroup: test-resourcegroup-1
  type: BareMetal
  hostIP: 10.10.10.3
  hostMAC: 26:72:25:44:44:6c 
  dpuIPs:
  - 172.18.0.5
  - 172.18.0.105
  hostAccess: IsolatedAccess
  identifier: forge2-worker
#---
#apiVersion: resource.vpc.forge.gitlab-master.nvidia.com/v1alpha1
#kind: ManagedResource
#metadata:
#  name: test-managedresource-dpu-2
#  namespace: forge-system
#spec:
#  resourceGroup: test-resourcegroup-1
#  type: BareMetal
#  hostIP: 10.10.10.2
#  hostMAC: b6:df:e6:bf:b8:a3 
#  dpuIPs:
#    - 172.18.0.6
#    - 172.18.0.106
#  hostAccess: FabricAccess
#  identifier: forge2-worker2
