apiVersion: resource.vpc.forge.gitlab-master.nvidia.com/v1alpha1
kind: ResourceGroup
metadata:
  name: test-resourcegroup-1
  namespace: forge-system
spec:
  tenantIdentifier: test-tenant
  network:
    ip: 10.10.10.0
    prefixLength: 24
    gateway: 10.10.10.1
  dhcpServer: 172.18.0.8
  networkImplementationType: Software
#---
#apiVersion: resource.vpc.forge.gitlab-master.nvidia.com/v1alpha1
#kind: ManagedResource
#metadata:
#  name: test-managedresource-dpu-1
#  namespace: forge-system
#spec:
#  resourceGroup: test-resourcegroup-1
#  type: BareMetal
#  hostIP: 10.10.10.2
#  hostMAC: 00:01:02:03:04:05
#  hostAccess: HostAccessIsolated
#  identifier: 00:01:02:03:04:05
#---
#apiVersion: resource.vpc.forge.gitlab-master.nvidia.com/v1alpha1
#kind: ManagedResource
#metadata:
#  name: test-managedresource-dpu-1
#  namespace: forge-system
#spec:
#  resourceGroup: test-resourcegroup-1
#  type: BareMetal
#  hostIP: 10.10.10.2
#  hostMAC: 00:01:02:03:04:05
#  hostAccess: HostAccessIsolated
#  identifier: 00:01:02:03:04:05
