[package]
name = "metrics-endpoint"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[dependencies]
hyper = { workspace = true }
hyper-util = { version = "^0.1", features = ["server", "http1", "http2", "tokio"] }
tokio = { workspace = true }
http-body-util = "^0.1"
bytes = "^1"

prometheus = "0.13.4"
tracing = "*"
eyre = "*"
opentelemetry = { workspace = true }
opentelemetry-semantic-conventions = { workspace = true, features = ["semconv_experimental"] }
opentelemetry-prometheus = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["spec_unstable_metrics_views"] }
