[package]
name = "metrics-endpoint"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[dependencies]
hyper = { version = "0.14", features = ["full"] }
prometheus = "0.13.4"
tracing = "*"
eyre = "*"
opentelemetry = { version = "0.21", features = ["logs"] }
opentelemetry-semantic-conventions = "0.13.0"
opentelemetry-prometheus = "0.14.1"
opentelemetry_sdk = { version = "0.21.1", features = ["logs", "rt-tokio"] }
