version: "3.9"

# NOTE: You need the docker loki log driver:
# `docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions`

networks:
  carbide:
    driver_opts:
      com.docker.network.bridge.name: carbide0
    ipam:
      config:
        - subnet: "172.20.0.0/24"
services:
  dhcp-relay:
    depends_on:
      - carbide-dhcp
    cap_add:
      - CAP_NET_ADMIN
    container_name: "dhcp-relay"
    networks:
      carbide:
        ipv4_address: 172.20.0.11
    image: carbide-runtime:latest
    command:
      - sh
      - -c
      - |
        apt-get update
        apt-get install libnl-3-dev libnl-route-3-dev libnl-genl-3-dev libjansson-dev libev-dev git -y
        git clone https://github.com/westermo/dhcp-helper.git
        cd dhcp-helper
        autoreconf -i
        ./configure
        make
        make install
        echo { \"option82\": { }, \"server\": [ { \"address\": \"172.20.0.12\" }], \"group\": [ { \"giaddr\": \"172.20.0.11\" } ] } > /etc/dhcphelper.json
        /usr/local/bin/dhcp-helper

  carbide-dhcp:
    depends_on:
      - loki
    build: dhcp
    networks:
      carbide:
        ipv4_address: 172.20.0.12
    ports:
      - "67:67/udp"
    volumes:
      - $HOME/docker_cargo_home:/docker_cargo_home
      - ./dev/certs:/opt/forge
      - .:/app/code
      - ca-certificate:/identity
    environment:
      - DISABLE_TLS_ENFORCEMENT=true
      - CARGO_HOME=/docker_cargo_home
      - FORGE_ROOT_CAFILE_PATH=/opt/forge/forge_root.pem
    command: cargo watch -C dhcp -x "build --target-dir /tmp/carbide-dhcp" -s "/usr/sbin/kea-dhcp4 -c /etc/kea/kea-dhcp4-carbide.conf"
    cap_add:
      - net_bind_service
    logging:
      driver: loki
      options:
        loki-url: "http://172.20.0.25:3100/loki/api/v1/push"

  carbide-db-migrations:
    depends_on:
      - postgresql
    build: api
    networks:
      carbide:
        ipv4_address: 172.20.0.13
    volumes:
      - $HOME/docker_cargo_home:/docker_cargo_home
      - .:/app/code
      - ca-certificate:/identity
    environment:
      - CARGO_HOME=/docker_cargo_home
    command: cargo watch -C api -x "run --target-dir /tmp/carbide-db-migrations -- migrate --datastore='postgres://carbide_development:notforprod@postgresql'"

  carbide-api:
    depends_on:
      - carbide-db-migrations
      - postgresql
      - loki
    build: api
    networks:
      carbide:
        ipv4_address: 172.20.0.14
    volumes:
      - $HOME/docker_cargo_home:/docker_cargo_home
      - ./dev/certs:/opt/forge
      - .:/app/code
      - ca-certificate:/identity
    # Options:
    #  - For trace/debug mode add '-dd':
    #    command: cargo watch -C api -x "run --target-dir /tmp/carbide-api -- -dd run [...]
    command:
      - sh
      - -c
      - >
        cargo build -p admin --target-dir /opt/forge-admin-cli/

        cargo watch -C api -x "run --target-dir /tmp/carbide-api --
        run --config-path=/app/code/dev/docker-env/carbide-api-config.toml"
    ports:
      - 1079:1079
      - 1080:1080
    environment:
      - DISABLE_TLS_ENFORCEMENT=true
      - CARGO_HOME=/docker_cargo_home
      - CARBIDE_API_DATABASE_URL=postgres://carbide_development:notforprod@postgresql
      - VAULT_KV_MOUNT_LOCATION=secret
      - VAULT_PKI_MOUNT_LOCATION=unsupported
      - VAULT_PKI_ROLE_NAME=unsupported
      - UNSUPPORTED_CERTIFICATE_PROVIDER=true
      - VAULT_TOKEN=notforprodtoken
      - VAULT_ADDR=http://vault:8200
      - RUST_BACKTRACE=full
      - RUST_LIB_BACKTRACE=0
      - RUST_LOG=$RUST_LOG
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: loki
      options:
        loki-url: "http://172.20.0.25:3100/loki/api/v1/push"

  carbide-pxe:
    depends_on:
      - loki
    build: pxe
    networks:
      carbide:
        ipv4_address: 172.20.0.15
    volumes:
      - $HOME/docker_cargo_home:/docker_cargo_home
      - ./dev/certs:/opt/forge
      - .:/app/code
      - ca-certificate:/identity
    environment:
      - DISABLE_TLS_ENFORCEMENT=true
      - CARGO_HOME=/docker_cargo_home
      - ROCKET_port=1080
      - FORGE_ROOT_CAFILE_PATH=/opt/forge/forge_root.pem
      - FORGE_CLIENT_CERT_PATH=/opt/forge/server_identity.pem
      - FORGE_CLIENT_KEY_PATH=/opt/forge/server_identity.key
      - ARTIFACT_AUTHORIZATION_USER=$ARTIFACT_AUTHORIZATION_USER
      - ARTIFACT_AUTHORIZATION_TOKEN=$ARTIFACT_AUTHORIZATION_TOKEN
    command: cargo watch -C pxe -x "run --target-dir /tmp/carbide-pxe"
    logging:
      driver: loki
      options:
        loki-url: "http://172.20.0.25:3100/loki/api/v1/push"

  postgresql:
    depends_on:
      - loki
    image: postgres:14.1-alpine
    networks:
      carbide:
        ipv4_address: 172.20.0.16
    volumes:
      - db-data:/var/lib/postgresql/data
      - ca-certificate:/identity
    environment:
      - POSTGRES_USER=${DBUSER:-carbide_development}
      - POSTGRES_DB=${DBNAME:-carbide_development}
      - POSTGRES_PASSWORD=${DBPASSWD:-notforprod}
    command: -c ssl=off
    ports:
      - 5432:5432
    logging:
      driver: loki
      options:
        loki-url: "http://172.20.0.25:3100/loki/api/v1/push"

  ntp:
    image: cturra/ntp
    networks:
      carbide:
        ipv4_address: 172.20.0.24
    ports:
      - "123:123/udp"
    cap_add:
      - net_bind_service

  vault:
    depends_on:
      - loki
    image: vault:latest
    networks:
      carbide:
        ipv4_address: 172.20.0.19
    cap_add:
      - ipc_lock
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=notforprodtoken
      - VAULT_KV_MOUNT_LOCATION=secret
      - VAULT_TOKEN=notforprodtoken
      - VAULT_ADDR=http://vault:8200
    healthcheck:
      interval: 1s
      timeout: 5s
      retries: 5
      test: [ "CMD", "vault", "status" ]
    volumes:
      - vault-data:/vault/file
      - ca-certificate:/identity
    domainname: metal.dev
    logging:
      driver: loki
      options:
        loki-url: "http://172.20.0.25:3100/loki/api/v1/push"

  carbide-dns:
    depends_on:
      - postgresql
      - carbide-api
      - loki
    build: dns
    networks:
      carbide:
        ipv4_address: 172.20.0.20
    volumes:
      - $HOME/docker_cargo_home:/docker_cargo_home
      - .:/app/code
    ports:
      - "1053:1053/udp"
    environment:
      - DISABLE_TLS_ENFORCEMENT=true
      - CARGO_HOME=/docker_cargo_home
    command: cargo watch -C dns -x "run --target-dir /tmp/carbide-dns -- run --carbide-url=http://172.20.0.14:1079"
    logging:
      driver: loki
      options:
        loki-url: "http://172.20.0.25:3100/loki/api/v1/push"

  prometheus:
    depends_on:
      - loki
    image: prom/prometheus:v2.41.0
    container_name: prometheus
    volumes:
      - ./dev/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      carbide:
        ipv4_address: 172.20.0.22
    logging:
      driver: loki
      options:
        loki-url: "http://172.20.0.25:3100/loki/api/v1/push"

  grafana:
    image: grafana/grafana:9.3.2
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./dev/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=forge
      - GF_SECURITY_ADMIN_PASSWORD=forge
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      carbide:
        ipv4_address: 172.20.0.23

  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    volumes:
      - ./dev/loki:/etc/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      carbide:
        ipv4_address: 172.20.0.25

volumes:
  ca-certificate: {}
  db-data: {}
  grafana-data: {}
  prometheus-data: {}
  vault-data: {}
