version: "3.9"

networks:
  carbide:
    driver_opts:
      com.docker.network.bridge.name: carbide0
    ipam:
      config:
        - subnet: "172.20.0.0/24"
services:
  dhcp-relay:
    depends_on:
      - carbide-dhcp
    container_name: "dhcp-relay"
    networks:
      carbide:
        ipv4_address: 172.20.0.11
    image: alpine:latest
    command: >
      sh -c "/sbin/apk add dhcp-helper && /usr/sbin/dhcp-helper -s carbide-dhcp -i eth0 -n -d"
  carbide-dhcp:
    depends_on:
      - terraform
    build: dhcp
    networks:
      carbide:
        ipv4_address: 172.20.0.12
    ports:
      - "67:67/udp"
    environment:
      - PROXY_IP=172.20.0.18
    volumes:
      - .:/app/code
      - ca-certificate:/identity
    command: cargo watch -C dhcp -x build -s "/usr/sbin/kea-dhcp4 -c /etc/kea/kea-dhcp4-carbide.conf"
    cap_add:
      - net_bind_service

  carbide-db-migrations:
    depends_on:
      - terraform
      - postgresql
    build: api
    networks:
      carbide:
        ipv4_address: 172.20.0.13
    volumes:
      - .:/app/code
      - ca-certificate:/identity
    command: cargo watch -C api -x "run -- migrate --datastore='postgres://carbide_development:notforprod@postgresql?sslmode=verify-full&sslrootcert=/identity/development-root-ca.pem'"

  carbide-api:
    depends_on:
      - terraform
      - carbide-db-migrations
      - postgresql
    build: api
    networks:
      carbide:
        ipv4_address: 172.20.0.14
    volumes:
      - .:/app/code
      - ca-certificate:/identity
    command: cargo watch -C api -x "run -- run --datastore='postgres://carbide_development:notforprod@postgresql?sslmode=verify-full&sslrootcert=/identity/development-root-ca.pem'"
    ports:
      - 1079:1079

  carbide-pxe:
    depends_on:
      - terraform
    build: pxe
    networks:
      carbide:
        ipv4_address: 172.20.0.15
    volumes:
      - .:/app/code
      - ca-certificate:/identity
    environment:
      - ROCKET_port=1080
    command: cargo watch -C pxe -x run

    
  postgresql:
    depends_on:
      - terraform
    image: postgres:14.1-alpine
    networks:
      carbide:
        ipv4_address: 172.20.0.16
    volumes:
      - db-data:/var/lib/postgresql/data
      - ca-certificate:/identity
    environment:
      - POSTGRES_USER=${DBUSER:-carbide_development}
      - POSTGRES_DB=${DBNAME:-carbide_development}
      - POSTGRES_PASSWORD=${DBPASSWD:-notforprod}
    command: -c ssl=on -c ssl_cert_file=/identity/postgresql.metal.dev.pem -c ssl_key_file=/identity/postgresql.metal.dev.key

  terraform:
    image: hashicorp/terraform:latest
    networks:
      carbide:
        ipv4_address: 172.20.0.17
    depends_on:
      vault:
        condition: service_healthy
    environment:
      - VAULT_TOKEN=notforprodtoken
      - VAULT_ADDR=http://vault:8200
      - TF_VAR_authority_output_root=/identity
    volumes:
      - ./dev/terraform:/infra
      - ca-certificate:/identity
      - terraform-state:/terraform
    working_dir: /infra
    domainname: metal.dev
    command: apply -auto-approve

  gateway:
    image: envoyproxy/envoy-dev:35f8d59b1172a85f02dd119791a9ef42c728cfa8
    networks:
      carbide:
        ipv4_address: 172.20.0.18
    ports:
      - "9901:9901"
      - "80:80"
      - "8080:8080"
    volumes:
      - ./dev/envoy.yaml:/etc/envoy/envoy.yaml
      - ca-certificate:/identity
    cap_add:
      - net_bind_service

  vault:
    image: vault:latest
    networks:
      carbide:
        ipv4_address: 172.20.0.19
    cap_add:
      - ipc_lock
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=notforprodtoken
      - VAULT_TOKEN=notforprodtoken
      - VAULT_ADDR=http://vault:8200
    healthcheck:
      interval: 1s
      timeout: 5s
      retries: 5
      test: [ "CMD", "vault", "status" ]
    volumes:
      - vault-data:/vault/file
      - ca-certificate:/identity
    domainname: metal.dev

  carbide-dns:
    depends_on:
      - terraform
      - postgresql
      - carbide-api
    build: dns
    networks:
      carbide:
        ipv4_address: 172.20.0.20
    volumes:
      - .:/app/code
    ports:
      - "1053:1053/udp"   
    command: cargo watch -C dns -x "run -- run --carbide-url=http://172.20.0.14:1079"

volumes:
  db-data: {}
  ca-certificate: {}
  vault-data: {}
  terraform-state: {}
