version: "3.9"

networks:
  carbide:
    driver_opts:
      com.docker.network.bridge.name: carbide0
    ipam:
      config:
        - subnet: "172.20.0.0/24"
services:
  dhcp-relay:
    depends_on:
      - carbide-dhcp
    cap_add:
      - CAP_NET_ADMIN
    container_name: "dhcp-relay"
    networks:
      carbide:
        ipv4_address: 172.20.0.11
    image: carbide-runtime:latest
    command:
      - sh
      - -c
      - |
        apt-get update
        apt-get install libnl-3-dev libnl-route-3-dev libnl-genl-3-dev libjansson-dev libev-dev git -y
        git clone https://github.com/westermo/dhcp-helper.git
        cd dhcp-helper
        autoreconf -i
        ./configure
        make
        make install
        echo { \"option82\": { }, \"server\": [ { \"address\": \"172.20.0.12\" }], \"group\": [ { \"giaddr\": \"172.20.0.11\" } ] } > /etc/dhcphelper.json
        /usr/local/bin/dhcp-helper

  carbide-dhcp:
    depends_on:
      - terraform
    build: dhcp
    networks:
      carbide:
        ipv4_address: 172.20.0.12
    ports:
      - "67:67/udp"
    volumes:
      - $HOME/docker_cargo_home:/docker_cargo_home
      - .:/app/code
      - ca-certificate:/identity
    environment:
      - CARGO_HOME=/docker_cargo_home
    command: cargo watch -C dhcp -x "build --target-dir /tmp/carbide-dhcp" -s "/usr/sbin/kea-dhcp4 -c /etc/kea/kea-dhcp4-carbide.conf"
    cap_add:
      - net_bind_service

  carbide-db-migrations:
    depends_on:
      - terraform
      - postgresql
    build: api
    networks:
      carbide:
        ipv4_address: 172.20.0.13
    volumes:
      - $HOME/docker_cargo_home:/docker_cargo_home
      - .:/app/code
      - ca-certificate:/identity
    environment:
      - CARGO_HOME=/docker_cargo_home
    command: cargo watch -C api -x "run --target-dir /tmp/carbide-db-migrations -- migrate --datastore='postgres://carbide_development:notforprod@postgresql?sslmode=verify-full&sslrootcert=/identity/development-root-ca.pem'"

  carbide-api:
    depends_on:
      - terraform
      - carbide-db-migrations
      - postgresql
    build: api
    networks:
      carbide:
        ipv4_address: 172.20.0.14
    volumes:
      - $HOME/docker_cargo_home:/docker_cargo_home
      - $HOME/docker_forge_root:/opt/forge
      - .:/app/code
      - ca-certificate:/identity
    # add '-dd' for trace/debug mode:
    # command: cargo watch -C api -x "run --target-dir /tmp/carbide-api -- -dd run [...]
    command: >-
      cargo watch -C api -x "run --target-dir /tmp/carbide-api --
      run
      --datastore='postgres://carbide_development:notforprod@postgresql?sslmode=verify-full&sslrootcert=/identity/development-root-ca.pem'
      --casbin-policy-file=/app/code/api/casbin-policy.csv
      --auth-permissive-mode=true"
    ports:
      - 1079:1079
      - 1080:1080
    environment:
      - CARGO_HOME=/docker_cargo_home
      - CARBIDE_DHCP_SERVER="172.20.0.12"
      - CARBIDE_METRICS_ENDPOINT=[::0]:1080
      - VAULT_MOUNT_LOCATION=secret
      - VAULT_TOKEN=notforprodtoken
      - VAULT_ADDR=http://vault:8200
      - RUST_BACKTRACE=1

  carbide-pxe:
    depends_on:
      - terraform
    build: pxe
    networks:
      carbide:
        ipv4_address: 172.20.0.15
    volumes:
      - $HOME/docker_cargo_home:/docker_cargo_home
      - .:/app/code
      - ca-certificate:/identity
    environment:
      - CARGO_HOME=/docker_cargo_home
      - ROCKET_port=1080
      - ARTIFACT_AUTHORIZATION_USER=$ARTIFACT_AUTHORIZATION_USER
      - ARTIFACT_AUTHORIZATION_TOKEN=$ARTIFACT_AUTHORIZATION_TOKEN
    command: cargo watch -C pxe -x "run --target-dir /tmp/carbide-pxe"

  postgresql:
    depends_on:
      - terraform
    image: postgres:14.1-alpine
    networks:
      carbide:
        ipv4_address: 172.20.0.16
    volumes:
      - db-data:/var/lib/postgresql/data
      - ca-certificate:/identity
    environment:
      - POSTGRES_USER=${DBUSER:-carbide_development}
      - POSTGRES_DB=${DBNAME:-carbide_development}
      - POSTGRES_PASSWORD=${DBPASSWD:-notforprod}
    command: -c ssl=on -c ssl_cert_file=/identity/postgresql.metal.dev.pem -c ssl_key_file=/identity/postgresql.metal.dev.key
    ports:
      - 5432:5432

  terraform:
    image: hashicorp/terraform:latest
    networks:
      carbide:
        ipv4_address: 172.20.0.17
    depends_on:
      vault:
        condition: service_healthy
    environment:
      - VAULT_MOUNT_LOCATION=secret
      - VAULT_TOKEN=notforprodtoken
      - VAULT_ADDR=http://vault:8200
      - TF_VAR_authority_output_root=/identity
    volumes:
      - ./dev/terraform:/infra
      - ca-certificate:/identity
      - terraform-state:/terraform
    working_dir: /infra
    domainname: metal.dev
    command: apply -auto-approve

  gateway:
    image: envoyproxy/envoy-dev:35f8d59b1172a85f02dd119791a9ef42c728cfa8
    networks:
      carbide:
        ipv4_address: 172.20.0.18
    ports:
      - "9901:9901"
      - "80:80"
      - "8080:8080"
    volumes:
      - ./dev/envoy.yaml:/etc/envoy/envoy.yaml
      - ca-certificate:/identity
    cap_add:
      - net_bind_service

  vault:
    image: vault:latest
    networks:
      carbide:
        ipv4_address: 172.20.0.19
    cap_add:
      - ipc_lock
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=notforprodtoken
      - VAULT_MOUNT_LOCATION=secret
      - VAULT_TOKEN=notforprodtoken
      - VAULT_ADDR=http://vault:8200
    healthcheck:
      interval: 1s
      timeout: 5s
      retries: 5
      test: [ "CMD", "vault", "status" ]
    volumes:
      - vault-data:/vault/file
      - ca-certificate:/identity
    domainname: metal.dev

  carbide-dns:
    depends_on:
      - terraform
      - postgresql
      - carbide-api
    build: dns
    networks:
      carbide:
        ipv4_address: 172.20.0.20
    volumes:
      - $HOME/docker_cargo_home:/docker_cargo_home
      - .:/app/code
    ports:
      - "1053:1053/udp"
    environment:
      - CARGO_HOME=/docker_cargo_home
    command: cargo watch -C dns -x "run --target-dir /tmp/carbide-dns -- run --carbide-url=http://172.20.0.14:1079"

  ipmi-console:
    depends_on:
      - carbide-db-migrations
      - postgresql
    build: api
    networks:
      carbide:
        ipv4_address: 172.20.0.21
    volumes:
      - $HOME/docker_cargo_home:/docker_cargo_home
      - .:/app/code
      - ca-certificate:/identity
    environment:
      - CARGO_HOME=/docker_cargo_home
    command: cargo watch -C ipmi/console -x "run --target-dir /tmp/ipmi-console -- run --datastore='postgres://carbide_development:notforprod@postgresql?sslmode=verify-full&sslrootcert=/identity/development-root-ca.pem' --listen='0.0.0.0:2222' --api-endpoint='http://172.20.0.14:1079'"
    ports:
      - 2222:2222

  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: prometheus
    volumes:
      - ./dev/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      carbide:
        ipv4_address: 172.20.0.22

  grafana:
    image: grafana/grafana:9.3.2
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./dev/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=forge
      - GF_SECURITY_ADMIN_PASSWORD=forge
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      carbide:
        ipv4_address: 172.20.0.23

volumes:
  ca-certificate: {}
  db-data: {}
  grafana-data: {}
  prometheus-data: {}
  terraform-state: {}
  vault-data: {}
