version: "3.9"
services:
  carbide-dhcp:
    build: dhcp
    volumes:
      - .:/app/code
    ports:
      - "67:67"
    expose:
      - "67/udp"
    command: cargo watch -C dhcp -x build -s "/usr/sbin/kea-dhcp4 -c /etc/kea/kea-dhcp4-carbide.conf"
    cap_add:
      - net_bind_service

  carbide-db-migrations:
    build: api
    volumes:
      - .:/app/code
    depends_on:
      - postgresql
    command: cargo watch -C api -x "run -- migrate --datastore=postgres://carbide_development:notforprod@postgresql"

  carbide-api:
    build: api
    volumes:
      - .:/app/code
    depends_on:
      - carbide-db-migrations
      - postgresql
    ports:
      - 1079:1079
    command: cargo watch -C api -x "run -- run --datastore=postgres://carbide_development:notforprod@postgresql"

  carbide-pxe:
    build: pxe
    volumes:
      - .:/app/code
    ports:
      - 1080:1080
    environment:
      - ROCKET_port=1080
    command: cargo watch -C pxe -x run

  postgresql:
    image: postgres:14.1-alpine
    volumes:
      - db-data:/var/lib/postgresql/db-data
    environment:
      - POSTGRES_USER=${DBUSER:-carbide_development}
      - POSTGRES_DB=${DBNAME:-carbide_development}
      - POSTGRES_PASSWORD=${DBPASSWD:-notforprod}
    ports:
      - 5432:5432
    expose:
      - 5432

  vault:
    image: vault:latest
    ports:
      - "8200:8200"
    cap_add:
      - ipc_lock
    expose:
      - 8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=notforprodtoken
    domainname: metal.dev

  terraform:
    image: hashicorp/terraform:latest
    depends_on:
      - vault
    environment:
      - VAULT_TOKEN=notforprodtoken
      - VAULT_ADDR=http://vault:8200
    volumes:
      - ./dev/terraform:/infra
    working_dir: /infra
    domainname: metal.dev

  gateway:
    image: envoyproxy/envoy-dev:35f8d59b1172a85f02dd119791a9ef42c728cfa8
    ports:
      - "9901:9901"
      - "80:80"
      - "8080:8080"
    expose:
      - 80
      - 8080
    volumes:
      - ./dev/envoy.yaml:/etc/envoy/envoy.yaml
    cap_add:
      - net_bind_service

volumes:
  db-data: {}
