- set:
    evpn:
      enable: on
    interface:
      lo:
        ip:
          address:
            {{.LoopbackIP}}/32: {}
        type: loopback
      p0:
        type: swp
      p1:
        type: swp
    nve:
      vxlan:
        enable: on
    router:
      bgp:
        autonomous-system: {{.ASN}}
        enable: on
        router-id: {{.LoopbackIP}}
      policy:
        prefix-list:
          {{.FromUnderlayFilter}}:
            rule:
              '65535':
                action: permit
                match:
                  any: {}
        route-map:
          {{.ToUnderlayFilter}}:
            rule:
              '65535':
                action:
                  permit: {}
    vrf:
      default:
        router:
          bgp:
            address-family:
              ipv4-unicast:
                enable: on
                redistribute:
                  connected:
                    enable: on
              l2vpn-evpn:
                enable: on
            enable: on
            neighbor:
              p0:
                peer-group: {{.UplinkGroup}}
                type: unnumbered
              p1:
                peer-group: {{.UplinkGroup}}
                type: unnumbered
            peer-group:
              {{.UplinkGroup}}:
                address-family:
                  ipv4-unicast:
                    policy:
                      inbound:
                        prefix-list: {{.FromUnderlayFilter}}
                      outbound:
                        route-map: {{.ToUnderlayFilter}}
                  l2vpn-evpn:
                    enable: on
                remote-as: external