ExternalConfigs: 
  - "shoreline"
Tests: 
  Cpu:
    BenchMark:
      CpuEcho1:
        ContainerImageName: "nvcr.io/nvidian/nvforge/machine-validation-runner:latest"
        ExecuteInHost: true
        Command: "echo "
        Desc: "Test desc"
        Args: " test"
        Contexts:
          - Discovery
          - Cleanup