---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  creationTimestamp: null
  name: leafs.networkfabric.vpc.forge.gitlab-master.nvidia.com
spec:
  group: networkfabric.vpc.forge.gitlab-master.nvidia.com
  names:
    kind: Leaf
    listKind: LeafList
    plural: leafs
    singular: leaf
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.control.managementIP
      name: mgmt-ip
      type: string
    - jsonPath: .spec.control.maintenanceMode
      name: maintenance
      type: string
    - jsonPath: .status.hostAdminIPs
      name: host-ip
      type: string
    - jsonPath: .status.conditions[0].status
      name: Status
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Leaf is the Schema for the leaf device API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: LeafSpec defines the desired state of Leaf
            properties:
              control:
                description: Control specifies the ways to interact with this Leaf
                  device.
                properties:
                  maintenanceMode:
                    description: MaintenanceMode is set to true when the controller
                      no longer actively configures the device.
                    type: boolean
                  managementIP:
                    description: ManagementIP is the management interface IP to access
                      this network device.
                    type: string
                  vendor:
                    description: Vendor is this network device's vendor.
                    type: string
                type: object
              hostAdminIPs:
                additionalProperties:
                  type: string
                description: HostAdminIPs are host IPs when hosts are not part of
                  any tenant networks, but still need to access the network for host
                  discovery, imaging, etc. The key-value pair is the leaf port and
                  the IP address assigned to the host interface connecting to the
                  leaf port
                type: object
              hostInterfaces:
                additionalProperties:
                  type: string
                description: HostInterfaces are host interfaces connected to this
                  Leaf. The key value pair is the host interface identifier and the
                  leaf port connected to the host interface.
                type: object
            type: object
          status:
            description: LeafStatus defines the observed state of Leaf
            properties:
              asn:
                description: ASN assigned to this leaf.
                format: int64
                maximum: 4294967295
                minimum: 0
                type: integer
              conditions:
                description: Conditions are the conditions of this Leaf device.
                items:
                  description: NetworkDeviceCondition indicates the transactions with
                    the network device.
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the last transaction time
                        for this ResourceGroup.
                      format: date-time
                      type: string
                    message:
                      description: Message is the response received from the network
                        device.
                      type: string
                    status:
                      description: Status is the network device status.
                      type: string
                    type:
                      description: Type is the network device condition type.
                      type: string
                  type: object
                type: array
              hostAdminDHCPServer:
                description: HostAdminDHCPServer is the DHCPServer for hosts in un-assigned
                  state.
                type: string
              hostAdminIPs:
                additionalProperties:
                  type: string
                description: HostAdminIPs are host IPs in un-assigned state.
                type: object
              loopbackIP:
                description: LoobackIP assigned to this leaf.
                type: string
              networkPolicies:
                description: NetworkPolicies applied to this Leaf.
                items:
                  type: string
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
