---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  creationTimestamp: null
  name: configurationresourcepools.networkfabric.vpc.forge.gitlab-master.nvidia.com
spec:
  group: networkfabric.vpc.forge.gitlab-master.nvidia.com
  names:
    kind: ConfigurationResourcePool
    listKind: ConfigurationResourcePoolList
    plural: configurationresourcepools
    singular: configurationresourcepool
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ConfigurationResourcePool is the Schema for the configurationresourcepools
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ConfigurationResourcePoolSpec defines the desired state of
              ConfigurationResourcePool
            properties:
              allocationBlockSize:
                description: AllocationBlockBitSize is allocation block size in bits.
                format: int32
                maximum: 268435455
                minimum: 0
                type: integer
              ranges:
                description: Range is the ConfigurationResourcePool half-open range
                  [Start, End).
                items:
                  description: PoolRange specify a continuous range.
                  properties:
                    end:
                      description: End is end of the PoolRange.
                      type: string
                    start:
                      description: Start is start of the PoolRange.
                      type: string
                  type: object
                type: array
              type:
                description: Type specifies the PoolRange type.
                type: string
            type: object
          status:
            description: ConfigurationResourcePoolStatus defines the observed state
              of ConfigurationResourcePool
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
