
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: managedresources.resource.vpc.forge.gitlab-master.nvidia.com
spec:
  group: resource.vpc.forge.gitlab-master.nvidia.com
  names:
    kind: ManagedResource
    listKind: ManagedResourceList
    plural: managedresources
    singular: managedresource
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.networkFabricReference.name
      name: fabric-device
      type: string
    - jsonPath: .spec.resourceGroup
      name: resourcegroup
      type: string
    - jsonPath: .status.hostAccessIPs.hostIP
      name: hostIP
      type: string
    - jsonPath: .status.hostAccessIPs.fabricIP
      name: fabricIP
      type: string
    - jsonPath: .status.conditions[0].status
      name: Status
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ManagedResource is the Schema for the managedresources API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ManagedResourceSpec defines the desired state of ManagedResource
            properties:
              State:
                description: State is ManagedResource's state.
                type: string
              dpuIPs:
                description: DPUIPs are IPs on DPU. if HostInterfaceAccess >= FabricAccess
                  it must contain second IP which will be used to access the host
                  from DC. This attribute is only required if ResourceGroup.Spec.NetworkImplementationType=Software
                items:
                  description: IPAddress is IPv4 or IPv6 Addresse types.
                  type: string
                type: array
              hostInterface:
                description: HostInterface uniquely identifies a host interface.
                type: string
              hostInterfaceAccess:
                description: HostInterfaceAccess specifies a host interface's accessibility.
                type: string
              hostInterfaceIP:
                description: HostInterfaceIP is the host interface IP of this ManagedResource.
                type: string
              hostInterfaceMAC:
                description: HostInterfaceMAC is the host MAC of this ManagedResource.
                type: string
              resourceGroup:
                description: ResourceGroup this ManagedResource belongs.
                type: string
              type:
                description: Type is this ManagedResource type.
                type: string
            type: object
          status:
            description: ManagedResourceStatus defines the observed state of ManagedResource
            properties:
              conditions:
                description: Conditions specify responses of ManagedResource create/delete/update.
                items:
                  description: ManagedResourceCondition defines responses of ManagedResource
                    create/delete/update.
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the last transaction time
                        for this ManagedResource.
                      format: date-time
                      type: string
                    message:
                      description: Message is message for the transaction.
                      type: string
                    reason:
                      description: Reason is reason for the transaction.
                      type: string
                    status:
                      description: Status is ManagedResourceCondition status.
                      type: string
                    type:
                      description: Type is ManagedResourceCondition type.
                      type: string
                  type: object
                type: array
              hostAccessIPs:
                description: HostAccessIPs are IPs to access the host from within
                  DC or from the public domain.
                properties:
                  fabricIP:
                    description: FabricIP is a network fabric IP routable within a
                      data center.
                    type: string
                  hostIP:
                    description: HostIP is an overlay IP assigned to the host.
                    type: string
                type: object
              networkFabricReference:
                description: NetworkFabricReference refers to a network fabric device
                  that this ManagedResource connects to.
                properties:
                  ConfigurationState:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                  port:
                    type: string
                type: object
              networkPolicies:
                description: NetworkPolicies applied to this ManagedResource.
                items:
                  type: string
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
