[package]
name = "dsocket"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = { features = ["all"] , workspace = true }
tracing = { features = ["log"] , workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
