[package]
name = "rpc"
version = "0.0.1"
license = "LicenseRef-NvidiaProprietary"
authors = ["NVIDIA Forge Engineering <swngc-forge-dev@exchange.nvidia.com>"]
edition.workspace = true

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
tonic = "0.8.0"
tonic-reflection = "0.5.0"

prost = "*"
prost-types = "*"
prost-build = "*"

uuid = { version = "1.0", features = ["v4", "serde"] }
mac_address = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
rust-fsm = "0.6.0"

[build-dependencies]
tonic-build = "0.8.0"
