[package]
name = "rpc"
version = "0.0.1"
edition = "2018"

[dependencies]
tonic = "0.8.0"
tonic-reflection = "0.5.0"

prost = "*"
prost-types = "*"
prost-build = "*"

uuid = "1.0"
mac_address = "*"
serde = { version = "*", features = ["derive"] }
rust-fsm = "0.6.0"

[build-dependencies]
tonic-build = "0.8.0"
