[package]
name = "rpc"
version = "0.1.0"
edition = "2018"

[dependencies]
tonic = "0.5"
tonic-reflection = "0.2"
prost = "0.8"
prost-types = "*"
uuid = "*"
serde = { version = "*", features = ["derive"] }

[build-dependencies]
tonic-build = "0.5"

