[package]
name = "rpc"
version = "0.0.1"
license = "LicenseRef-NvidiaProprietary"
authors = ["NVIDIA Forge Engineering <swngc-forge-dev@exchange.nvidia.com>"]
edition.workspace = true

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
eyre = "0.6"
hyper = "0.14"
hyper-rustls = { version = "0.23", features = ["http1", "http2"] }
lazy_static = "1.4"
mac_address = "*"
prost = "*"
prost-build = "*"
prost-types = "*"
rustls-pemfile = "1.0"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tokio = { workspace = true }
tokio-rustls = { version = "0.23", features = ["dangerous_configuration"] }
tonic = { workspace = true }
tonic-reflection = "0.5.0"
tower = "0.4.13"
uuid = { version = "1.0", features = ["v4", "serde"] }

[build-dependencies]
tonic-build = "0.8.0"
