apiVersion: resource.vpc.forge.gitlab-master.nvidia.com/v1alpha1
kind: ManagedResource
metadata:
  name: mr-1
  namespace: forge-system
spec:
  resourceGroup: internal
  type: BareMetal
  hostInterfaceIP: 20.10.11.2
  hostInterface: forge4-en0
  # hostInterfaceAccess: IsolatedAccess
  hostInterfaceAccess: FabricAccessDirect
