[package]
name = "dsocket"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
authors = ["NVIDIA Forge Engineering <swngc-forge-dev@exchange.nvidia.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = { version = "0.5.5", features=["all"]}
tracing = { version = "0.1.40", features=["log"] }
tokio = { workspace = true }
