[package]
name = "sqlx-testing"
version = "0.0.1"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[lib]
name = "sqlx_testing"

[dependencies]
sqlx = { workspace = true }
sqlx-core = { workspace = true }
tokio = { workspace = true }

# [local-dependencies]
carbide-api = { path = "../../api", default-features = false }

[features]
linux-build = ["carbide-api/linux-build"]



[lints]
workspace = true
