[package]
name = "carbide-dns"
version = "0.0.1"
edition = "2021"
description = "Carbide is bare metal provisioning system with auto-discovery and API based machine manipulation"


[[bin]]
name = "carbide-dns"
path = "src/main.rs"

[dependencies]
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "mac_address", "ipnetwork", "uuid", "migrate", "postgres", "chrono", "macros" ]}
tokio = { version = "1.9", features = ["full"] }
trust-dns = { version = "0.21.1" }

[dev-dependencies]
rstest = "*"
