[package]
name = "carbide-dns"
version = "0.0.1"
edition = "2021"
description = "Carbide is bare metal provisioning system with auto-discovery and API based machine manipulation"

[[bin]]
name = "carbide-dns"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.43"
clap = { version = "~3", features = ["derive"] }
color-eyre = "0.5.11"
futures = "0.3"
itertools = "*"
log = { version = "*" }
pretty_env_logger = "*"
rpc = { path = "../rpc" }
sqlx = { version = "0.5", features = ["runtime-tokio-rustls", "mac_address", "ipnetwork", "uuid", "migrate", "postgres", "chrono", "macros"] }
thiserror = "1.0"
tokio = { version = "1.9", features = ["full"] }
tonic = { version = "0.7.0", features = ["tls"] }
trust-dns-server = { version = "0.21.1" }

[dev-dependencies]
rstest = "*"
