[package]
name = "forge-http-connector"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hickory-resolver = { version = "0.24.0" }
tokio = { workspace = true, features = ["rt", "macros"] }
tracing = "0.1.40"
socket2 = "0.5.5"
hyper = { workspace = true, features = [
    "client",
] }
hyper-util = { version = "0.1.10", features = ["tokio"] }

futures-util = "0.3.28"
tower-service = "0.3.2"
tokio-socks = "0.5.1"
tryhard = "0.5.1"

# [local-dependencies]
dsocket = { path = "../dsocket" }

[dev-dependencies]
hyper = { workspace = true, features = [
    "client",
    "http1",
    "http2",
] }
tokio = { workspace = true, features = ["rt", "macros"] }
