[package]
name = "vpc-mock"
version = "0.1.0"
edition.workspace = true
description = "TODO TODO TDO"
license = "LicenseRef-NvidiaProprietary"
authors = ["NVIDIA Forge Engineering <swngc-forge-dev@exchange.nvidia.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.4"
axum-server = { version = "0.4.4", features = ["tls-rustls"] }
clap = { version = "~3", features = ["derive", "env"] }
tokio.workspace = true
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.91"

