apiVersion: apps/v1
kind: Deployment
metadata:
  name: kea-dhcp-deployment
  labels:
    app: kea-dhcp
spec:
  selector:
    matchLabels:
      app: kea-dhcp
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kea-dhcp
    spec:
      containers:
        - name: kea-dhcp
          image: carbide:latest
          command: ["/sbin/kea-dhcp4"]
          args:
            - '-c'
            - '/tmp/kea_config.conf'
          volumeMounts:
            - name: config-volume
              mountPath: "/tmp"
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
          imagePullPolicy:  IfNotPresent
          ports:
            - containerPort: 67 
      volumes:
      - name: config-volume
        configMap:
          name: kea-dhcp-configuration
