apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: carbide-dhcp
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: kea-dhcp-configuration
    behavior:  create
    files:
    - kea_config.conf=kea.json