[package]
name = "console"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "ipmi-proxy"
path = "src/main.rs"

[dependencies]
uuid = { version = "0.8.2", features = ["v4", "serde"] }
carbide-api = { path = "../../api" }
sqlx = { version = "0.5", features = [ "mac_address", "ipnetwork", "uuid", "migrate", "postgres", "chrono", "macros", "json" ] }
tokio = { version = "1.9", features = ["full"] }
tokio-stream = "*"

thrussh = { version = "0.33.5", features = ["openssl"]}
thrussh-keys = { version = "0.21.0", features = ["openssl"]}
futures = { version = "0.3.21" }
anyhow = { version = "1.0.53" }
log = { version = "*", features = ["serde"] }
pretty_env_logger = "*"
color-eyre = "0.5.11"
clap = { version = "~3", features = ["derive"] }

lazy_static = "1.4.0"
