listen="[::]:1081"
metrics_endpoint="[::]:1080"
database_url="postgres://specified_as_env_variable"
asn=65535
dhcp_servers=["172.20.0.12"]
route_servers=[]
rapid_iterations=false

[auth]
auth_permissive_mode=false
casbin_policy_file="/app/code/api/casbin-policy.csv"
