[lo-ip]
type = "ipv4"
ranges = [{ start = "10.180.62.1", end = "10.180.62.62" }]

[vlan-id]
type = "integer"
ranges = [{ start = "100", end = "501" }]

[vni]
type = "integer"
ranges = [{ start = "1024500", end = "1024550" }]
