[default]
address = "0.0.0.0"
carbide_api_url = "http://10.144.151.57:22079"
carbide_pxe_url = "http://172.20.0.2:8080"
carbide_ntp_server = "172.20.0.2"
port = 8000

[development]
template_dir = "/opt/carbide/pxe/templates"

[production]
template_dir = "/opt/carbide/pxe/templates"
