# permissions for end users to view configurationresourcepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configurationresourcepool-viewer-role
rules:
- apiGroups:
  - networkfabric.vpc.forge.gitlab-master.nvidia.com
  resources:
  - configurationresourcepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networkfabric.vpc.forge.gitlab-master.nvidia.com
  resources:
  - configurationresourcepools/status
  verbs:
  - get
