# permissions for end users to view managedresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedresource-viewer-role
rules:
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - managedresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - managedresources/status
  verbs:
  - get
