# permissions for end users to view sharedresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sharedresource-viewer-role
rules:
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - sharedresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - sharedresources/status
  verbs:
  - get
