[package]
name = "forge-host-support"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# [local-dependencies]
forge-tls = { path = "../tls" }
logfmt = { path = "../logfmt" }
rpc = { path = "../../rpc" }
utils = { path = "../utils" }
forge-uuid = { path = "../uuid" }

base64 = "0.22.1"
csv = "1.2.1"
eyre = "*"
ipnetwork = { workspace = true }
libudev = { version = "0.3", optional = true }
procfs = { version = "0.17", optional = true }
regex = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smbios-lib = "0.9.0"
thiserror = "2"
tokio = { workspace = true }
toml = "0.8.8"
tonic = { workspace = true }
tracing = "*"
tracing-subscriber = { version = "*", features = ["env-filter", "local-time"] }
tryhard = "0.5.1"
uname = "0.1"
uuid = "1.0"
serde_with = "3.12.0"

[lints]
workspace = true

[features]
default = ["linux-build"]
linux-build = ["libudev", "procfs"]
