apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbide-api-deployment
spec:
  template:
    spec:
      serviceAccountName: vpc-controller-manager
      containers:
        - name: carbide-api
          imagePullPolicy: Always
          command: ["/bin/sh", "-c", "/opt/carbide/carbide-api run --datastore=\"${CARBIDE_API_DATASTORE}\" --listen=\"127.0.0.1:1079\""]
          env:
            - name: CARBIDE_API_DATASTORE
              valueFrom: { secretKeyRef: { name: carbide-postgres-pguser-carbide-postgres, key: uri } }
            - name: VAULT_ADDR
              value: http://vault:8200
            - name: VAULT_MOUNT_LOCATION
              value: secrets
            - name: VAULT_TOKEN
              value: notforprodtoken
            - name: CARBIDE_DHCP_SERVER
              value: 127.0.0.1
      imagePullSecrets:
        - name: imagepullsecret
