[package]
name = "carbide-ssh-console-mock-api-server"
version = "0.0.0"
edition.workspace = true

[lib]
# TODO: rename to carbide_ssh_console_mock_api_server in source
name = "ssh_console_mock_api_server"

[dependencies]

# local dependencies
carbide-version = { path = "../../common/version" }
carbide-api-test-helper = { path = "../../common/api-test-helper" }
carbide-rpc = { path = "../../rpc" }
carbide-uuid = { path = "../../common/uuid" }

tonic = { version = "0.14", features = ["tls-ring"] }
tonic-prost = "0.14"
tonic-prost-build = "0.14"
prost = "0.14.1"
prost-types = "0.14.1"
tokio = { version = "1.45.1", features = ["macros"] }
tracing = "0.1.41"
uuid = "1.17.0"
eyre = "0.6.12"
rustls = { workspace = true, features = ["ring"] }
rustls-pemfile = "2.2.0"

[build-dependencies]
carbide-version = { path = "../../common/version" }
tonic-prost-build = "0.14"
