[package]
name = "logfmt"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
tracing = "*"
tracing-subscriber = { version = "*" }

[dev-dependencies]
tracing-subscriber = { version = "*", features = ["env-filter", "local-time"] }
