[package]
name = "mlxconfig-variables"
version = "0.1.0"
edition = "2021"
description = "Type definitions for Mellanox hardware configuration registry."

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
hex = "0.4.3"

[dev-dependencies]
serde_json = "1.0"
