[package]
name = "carbide-uuid"
version = "0.0.0"
edition.workspace = true
description = "Common UUID types Forge components."
license-file.workspace = true
authors.workspace = true

# TODO: rename to carbide_uuid in source
[lib]
name = "forge_uuid"

[features]
sqlx = ["dep:sqlx"]

[dependencies]
data-encoding = "2.3.3"
eyre = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
sha2 = "0.10.3"
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "mac_address", "ipnetwork", "uuid", "migrate", "postgres", "chrono", "macros", "json"], optional = true }
thiserror = "2.0"
tonic = { workspace = true }
uuid = { version = "1.0", features = ["v4", "serde"] }
prost = "0.14.1"

[lints]
workspace = true
