[package]
name = "forge-uuid"
version = "0.0.1"
edition.workspace = true
description = "Common UUID types Forge components."
license-file.workspace = true
authors.workspace = true

[dependencies]
data-encoding = "2.3.3"
eyre = "*"
prettytable-rs = "^0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
sha2 = "0.10.3"
sqlx = { version = "0.7.1", features = [
    "runtime-tokio-rustls",
    "mac_address",
    "ipnetwork",
    "uuid",
    "migrate",
    "postgres",
    "chrono",
    "macros",
    "json",
] }
thiserror = "1.0"
tonic = { workspace = true }
uuid = { version = "1.0", features = ["v4", "serde"] }


rpc = { path = "../../rpc" }
utils = {path = "../utils" }