analytics:
  reporting_enabled: false
auth_enabled: false
common:
  compactor_address: 'loki'
  path_prefix: /tmp/loki
  replication_factor: 1
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
compactor:
  compaction_interval: 10m
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  retention_enabled: true
frontend:
  scheduler_address: ""
frontend_worker:
  scheduler_address: ""
index_gateway:
  mode: ring
ingester:
  chunk_encoding: snappy
limits_config:
  enforce_metric_name: false
  ingestion_burst_size_mb: 32
  ingestion_rate_mb: 16
  max_cache_freshness_per_query: 10m
  per_stream_rate_limit: 16MB
  per_stream_rate_limit_burst: 16MB
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 720h
  split_queries_by_interval: 15m
memberlist:
  join_members:
  - loki-memberlist
query_range:
  align_queries_with_step: true
ruler:
  storage:
    type: local
schema_config:
  configs:
  - from: "2022-01-11"
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      period: 24h
      prefix: loki_index_
server:
  grpc_listen_port: 9096
  http_listen_port: 3100
storage_config:
  hedging:
    at: 250ms
    max_per_second: 20
    up_to: 3
