[package]
name = "carbide-dpf"
version = "0.0.1"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "carbide_dpf"

[dependencies]
kube = { version = "3.0.0", default-features = false, features = [
  "runtime",
  "derive",
  "client",
  "openssl-tls",
] }
rustls = { workspace = true }
k8s-openapi = { version = "0.27.0", features = ["latest", "schemars"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tera = { workspace = true }
eyre = { workspace = true }
tracing = { workspace = true }
uuid = { version = "1.17.0", features = ["v4"] }
async-trait = { workspace = true }

[dev-dependencies]
tower-test = "0.4"
hyper = { version = "0.14", features = ["client", "http1"] }
http = "1.3.1"
once_cell = "1.19"

[lints]
workspace = true
