[package]
name = "carbide-measured-boot"
version = "0.0.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[lib]
name = "measured_boot"

[features]
sqlx = ["dep:sqlx", "carbide-uuid/sqlx"]
cli = ["dep:prettytable-rs", "dep:eyre", "dep:clap", "carbide-rpc/cli"]

[dependencies]
# workspace dependencies
carbide-uuid = { path = "../uuid" }
carbide-rpc = { path = "../../rpc" }

thiserror = "2"
sqlx = { workspace = true, optional = true }
prettytable-rs = { version = "0.10", optional = true }
clap = { workspace = true, optional = true }
eyre = { version = "0.6", optional = true }
serde = "1"
chrono = "0.4"
tonic = { workspace = true }

[lints]
workspace = true
