apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: carbide:latest
    newName: quay.io/nvidia/nvmetal-carbide
    newTag: v0.0.1-54-g24109162
resources:
  - resources/forge-system.yaml
  - forge
