[package]
name = "carbide-health"
version = "0.0.1"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[[bin]]
# TODO: rename to carbide-hw-health
name = "forge-hw-health"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
clap = { workspace = true }
chrono = { workspace = true }
eyre = { workspace = true }
futures = { workspace = true }
libredfish = { workspace = true }
humantime = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true, features = ["tokio"] }
http-body-util = { workspace = true }
lazy_static = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true, features = ["grpc-tonic"] }
opentelemetry_sdk = { workspace = true }
opentelemetry-prometheus = { workspace = true }
prometheus = { workspace = true }
serde = { features = ["derive"], workspace = true }
serde_json = { workspace = true }
# The "*" version has old `digest` who's `subtle` conflicts with reqwest
sha2 = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { features = [
  "env-filter",
  "local-time",
], workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }

# [local-dependencies]
carbide-health-report = { path = "../health-report" }
carbide-rpc = { path = "../rpc" }
carbide-tls = { path = "../tls" }
carbide-version = { path = "../version" }
carbide-utils = { path = "../utils" }
carbide-uuid = { path = "../uuid" }

[build-dependencies]
carbide-version = { path = "../version" }

[lints]
workspace = true
