[default]
address = "0.0.0.0"
carbide_api_url = "http://carbide-carbide-api-http:12079"

# TODO(ajf): No MetalLB so we have to point this at just one of the nodes
carbide_pxe_url = "http://10.180.248.29:8080"
carbide_ntp_server = "10.23.138.62"
port = 8000

[development]
template_dir = "/opt/carbide/pxe/templates"

[production]
template_dir = "/opt/carbide/pxe/templates"
