# service to expose the ovnkube-db pod
apiVersion: v1
kind: Service
metadata:
  name: ovn-central
  namespace: forge-system
spec:
  selector:
    app: ovn-central
  ports:
    - name: north
      port: 6641
      protocol: TCP
      targetPort: 6641
    - name: south
      port: 6642
      protocol: TCP
      targetPort: 6642
  sessionAffinity: None
  type: ClusterIP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ovn-central
  namespace: forge-system
  labels:
    app: ovn-central
spec:
  selector:
    matchLabels:
      app: ovn-central
  replicas: 1
  template:
    metadata:
      labels:
        app: ovn-central
    spec:
      containers:
        - name: ovn-central
          image: "quay.io/nvidia/forge-connectivity:latest"
          imagePullPolicy: "IfNotPresent"
          command:
            - /start_ovn_central.sh
          securityContext:
            runAsUser: 0
            capabilities:
              add: ["SYS_NICE"]
          terminationMessagePolicy: FallbackToLogsOnError
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
          env:
            - name: OVN_SSL_ENABLE
              value: "no"
            - name: OVN_CERT_PATH
              value: /ovn-cert
          volumeMounts:
            - name: ovn-cert
              mountPath: /ovn-cert
      volumes:
        - name: ovn-cert
          secret:
            secretName: ovn-central-cert
      #nodeSelector:
      #  vpc.forge.nvidia.com/node: control
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ovn-central-cert
  namespace: forge-system
spec:
  dnsNames:
    - ovn-central.forge-system.svc
    - ovn-central.forge-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: forge-caissuer
  secretName: ovn-central-cert
