[package]
name = "forge-ssh"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true


[dependencies]
tokio = { workspace = true }
tonic = { workspace = true }
ssh2 = { version = "0.9" }
openssl = { version = "0.10", features = ["aws-lc"] }
humantime = "2.1.0"
thiserror = "2.0.3"
tracing = "*"


[lints]
workspace = true
