[package]
name = "carbide-ssh"
version = "0.0.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

# TODO: rename to carbide_ssh in source
[lib]
name = "forge_ssh"

[dependencies]
tokio = { workspace = true }
tonic = { workspace = true }
ssh2 = { version = "0.9" }
openssl = { version = "0.10", features = ["aws-lc"] }
humantime = "2.1.0"
thiserror = "2.0.3"
tracing = "*"


[lints]
workspace = true
