[package]
name = "carbide-ssh"
version = "0.0.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

# TODO: rename to carbide_ssh in source
[lib]
name = "forge_ssh"

[dependencies]
tokio = { workspace = true }
tonic = { workspace = true }
ssh2 = { workspace = true }
openssl = { features = ["aws-lc"] , workspace = true }
humantime = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }


[lints]
workspace = true
