[package]
name = "otel-agent"
version = "0.0.1"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[[bin]]
name = "forge-dpu-otel-agent"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
eyre = "*"
humantime = "*"
rand = "0.8"
tracing = "*"
tonic = { workspace = true }
tokio = { workspace = true }

# [local-dependencies]
forge-certs = { path = "../../certs" }
forge-host-support = { path = "../../../common/host-support" }
forge-systemd = { path = "../../systemd" }
forge-tls = { path = "../../../common/tls" }
rpc = { path = "../../../rpc" }

[dev-dependencies]
ctor = "0.2"
tempfile = "3"
prost = "0.13"
reqwest = { version = "*", default-features = false, features = [
    "rustls-tls",
    "stream",
] }
rustls-pemfile = "2.2.0"
rustls-pki-types = "1.10.0"
