[package]
name = "carbide-dpu-otel-agent"
version = "0.0.1"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[lib]
name = "otel_agent"

[[bin]]
# TODO: rename to carbide-dpu-otel-agent
name = "forge-dpu-otel-agent"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
eyre = "*"
humantime = "*"
rand = "0.9"
thiserror = "2.0.3"
tonic = { workspace = true }
tokio = { workspace = true }
tracing = "*"
tracing-subscriber = { version = "*", features = ["env-filter", "local-time"] }
typed-builder = "0.20.0"

# [local-dependencies]
carbide-certs = { path = "../../certs" }
carbide-host-support = { path = "../../../common/host-support" }
carbide-systemd = { path = "../../systemd" }
carbide-tls = { path = "../../../common/tls" }
carbide-rpc = { path = "../../../rpc" }

[dev-dependencies]
ctor = "0.2"
tempfile = "3"
prost = "0.14.1"
reqwest = { version = "*", default-features = false, features = [
    "rustls-tls",
    "stream",
] }
rustls-pemfile = "2.2.0"
rustls-pki-types = "1.10.0"

[lints]
workspace = true
