[package]
name = "admin"
version = "0.0.1"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[[bin]]
name = "forge-admin-cli"
path = "src/main.rs"

[dependencies]
byte-unit = "4.0.19"
chrono = "0.4.34"
clap = { workspace = true }
clap_complete = "*"
color-eyre = "*"
libredfish = { version = "0.17.1", registry = "sw-ngc-forge-cargo-local" }
prettytable-rs = "^0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9.25"
thiserror = "1"
tracing = "*"
tracing-subscriber = { version = "*", features = ["env-filter", "local-time"] }
tokio = { workspace = true }
tonic = { workspace = true }
uuid = "1.0"

# [local-dependencies]
forge-tls = { path = "../common/tls" }
forge-version = { path = "../common/version" }
rpc = { path = "../rpc" }
utils = { path = "../common/utils" }
forge_secrets = { path = "../common/secrets" }

[build-dependencies]
clap = { workspace = true }
forge-version = { path = "../common/version" }
rpc = { path = "../rpc" }
