[package]
name = "admin"
version = "0.0.1"
edition.workspace = true
license = "LicenseRef-NvidiaProprietary"
authors = ["NVIDIA Forge Engineering <swngc-forge-dev@exchange.nvidia.com>"]

[[bin]]
name = "forge-admin-cli"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
color-eyre = "*"
libredfish = { version = "0.6.0", registry = "sw-ngc-forge-cargo-local" }
log = "*"
pretty_env_logger = "*"
prettytable-rs = "^0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio = { workspace = true }
toml = "0.7.3"
tonic = { workspace = true }
uuid = "1.0"

# local crate dependencies
rpc = { path = "../rpc" }
