[package]
name = "admin"
version = "0.0.1"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[[bin]]
name = "forge-admin-cli"
path = "src/main.rs"

[dependencies]
byte-unit = "5.1.6"
chrono = "0.4.34"
clap = { workspace = true }
clap_complete = "*"
color-eyre = "*"
eyre = "*"
figment = { version = "0.10.10", features = ["env", "toml"] }
libredfish = { workspace = true }
mac_address = "1.1.2"
prettytable-rs = "^0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9.25"
thiserror = "2"
tracing = "*"
tracing-subscriber = { version = "*", features = ["env-filter", "local-time"] }
tokio = { workspace = true }
tonic = { workspace = true }
uuid = "1.0"
x509-parser = { version = "0.16.0", features = ["validate"] }
strum_macros = "*"
strum = "*"

# [local-dependencies]
bmc-vendor = { path = "../common/bmc-vendor" }
carbide-api = { path = "../api" }
# Note: enabling sqlx feature is temporary so that carbide-api can build, until we can eliminate the carbide-api dependency
config-version = { path = "../common/config-version", features = ["sqlx"] }
forge-network = { path = "../common/network" }
forge-tls = { path = "../common/tls" }
forge-uuid = { path = "../common/uuid" }
forge-version = { path = "../common/version" }
health-report = { path = "../common/health-report" }
rpc = { path = "../rpc" }
utils = { path = "../common/utils", features = ["sqlx"] } # sqlx feature is temporary, see above
forge_secrets = { path = "../common/secrets" }

[build-dependencies]
clap = { workspace = true }
forge-version = { path = "../common/version" }
rpc = { path = "../rpc" }
