[package]
name = "admin"
version = "0.0.1"
edition.workspace = true
license = "LicenseRef-NvidiaProprietary"
authors = ["NVIDIA Forge Engineering <swngc-forge-dev@exchange.nvidia.com>"]

[[bin]]
name = "forge-admin-cli"
path = "src/main.rs"

[dependencies]
clap = { version = "~3", features = ["derive", "env"] }
color-eyre = "0.6"
log = "0.4"
pretty_env_logger = "0.4"
prettytable-rs = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio = { workspace = true }
tonic = "0.8"
uuid = "1.0"

# local crate dependencies
rpc = { path = "../rpc" }
