[package]
name = "admin"
version = "0.0.1"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[[bin]]
name = "forge-admin-cli"
path = "src/main.rs"

[dependencies]
chrono = "0.4.34"
clap = { workspace = true }
clap_complete = "*"
color-eyre = "*"
eyre = "*"
libredfish = { workspace = true }
mac_address = "1.1.2"
prettytable-rs = "^0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9.25"
tracing = "*"
tracing-subscriber = { version = "*", features = ["env-filter", "local-time"] }
tokio = { workspace = true }
tonic = { workspace = true }
uuid = "1.0"
x509-parser = { version = "0.17.0", features = ["validate"] }
toml = "0.8.8"
ssh2 = "0.9"

# [local-dependencies]
bmc-vendor = { path = "../common/bmc-vendor" }
forge-network = { path = "../common/network" }
forge-tls = { path = "../common/tls" }
forge-uuid = { path = "../common/uuid" }
forge-version = { path = "../common/version" }
health-report = { path = "../common/health-report" }
rpc = { path = "../rpc" }
utils = { path = "../common/utils" }
forge_secrets = { path = "../common/secrets" }
measured-boot = { path = "../common/measured-boot", features = ["cli"] }
ipnet = "2.10.1"

[build-dependencies]
clap = { workspace = true }
forge-version = { path = "../common/version" }
