---
apiVersion: v1
kind: Service
metadata:
  name: carbide-api-http-external
spec:
  selector:
    app: carbide-api
  ports:
    - nodePort: 22079
      port: 22079
      protocol: TCP
      targetPort: 12079
  type: NodePort
