[default]
address = "0.0.0.0"
carbide_api_url = "http://10.23.138.62:22079"
carbide_pxe_url = "http://10.23.138.62:8080"
port = 8000

[development]
template_dir = "/opt/carbide/pxe/templates"

[production]
template_dir = "/opt/carbide/pxe/templates"
