[package]
name = "config-version"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[features]
sqlx = ["dep:sqlx"]

[dependencies]
chrono = "0.4.34"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "mac_address", "ipnetwork", "uuid", "migrate", "postgres", "chrono", "macros", "json"], optional = true }
thiserror = "2.0"

[lints]
workspace = true
