admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

node:
  cluster: envoy-pxe
  id: envoy-id-pxe

static_resources:
  listeners:
  - name: http-pxe
    address:
      socket_address: { address: 0.0.0.0, port_value: 8083}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
                - match: { prefix: "/", grpc: {}}
                  route: { cluster: carbide-pxe }
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  - name: https-pxe
    address:
      socket_address: { address: 0.0.0.0, port_value: 8088}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
                - match: { prefix: "/" }
                  route: { cluster: carbide-pxe }
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      transport_socket:
        name: envoy.transport_socket.tls
        typed_config:
           "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
           common_tls_context:
              tls_certificate_sds_secret_configs:
                name: tls_sds
                sds_config:
                  resource_api_version: V3
                  path_config_source:
                    path: /tmp/envoy-tls/tls_certificate_sds_secret.yaml
              validation_context_sds_secret_config:
                name: validation_context_sds
                sds_config:
                  resource_api_version: v3
                  path_config_source:
                    path: /tmp/envoy-ca/validation_context_sds_secret.yaml

  clusters:
  - name: carbide-pxe
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    load_assignment:
      cluster_name: carbide
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8000
