[default]
address = "0.0.0.0"
carbide_api_url = "http://10.180.32.10:22079"
carbide_pxe_url = "http://10.180.32.10:8080"
carbide_ntp_server = "10.180.37.3"
port = 8000

[development]
template_dir = "/opt/carbide/pxe/templates"

[production]
template_dir = "/opt/carbide/pxe/templates"
