[package]
name = "mqttea-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mqttea-example"
path = "src/main.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.4", features = ["derive"] }
rumqttc = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
prost = "0.12"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
mqttea = { path = "../../common/mqttea" }

[build-dependencies]
prost-build = "0.12"
