apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbide-relay-deployment
  labels:
    app: carbide-relay
spec:
  selector:
    matchLabels:
      app: carbide-relay
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: carbide-relay
    spec:
      hostNetwork: true
      containers:
        - name: carbide-relay
          image: alpine:latest
          command: ["/bin/sh", "-c", "apk add dhcp-helper && /usr/sbin/dhcp-helper -s 10.96.0.2 -i eth0 -n -d"]
          imagePullPolicy:  IfNotPresent
          ports:
            - containerPort: 67
            - containerPort: 68
