apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - ./carbide-relay
  - coredns.yaml
patchesStrategicMerge:
  - local_services.yaml
vars:
  - name: CARBIDE_DNS_SERVICE_IP
    objref:
      kind: Service
      name: carbide-dns
      apiVersion: v1
    fieldref: 
      fieldPath: spec.clusterIP
