[package]
name = "health"
version = "0.0.1"
edition.workspace = true
license = "LicenseRef-NvidiaProprietary"
authors = ["NVIDIA Forge Engineering <swngc-forge-dev@exchange.nvidia.com>"]

[[bin]]
name = "forge-hw-health"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
eyre = "*"
hyper = "*"
http = "*"
libredfish = { version = "0.11.0", registry = "sw-ngc-forge-cargo-local" }
opentelemetry-prometheus = "*"
opentelemetry = "*"
opentelemetry_api = "*"
opentelemetry_sdk = "*"
prometheus = "*"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "*"
tracing = "*"
thiserror = "1"
tokio = { workspace = true }
tonic = { workspace = true }

# local crate dependencies
rpc = { path = "../rpc" }
forge-version = { path = "../version" }
utils = { path = "../utils" }

[build-dependencies]
forge-version = { path = "../version" }
