[package]
name = "health"
version = "0.0.1"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[[bin]]
name = "forge-hw-health"
path = "src/main.rs"

[dependencies]
base64 = "0.21.5"
clap = { workspace = true }
chrono = "*"
eyre = "*"
libredfish = { version = "0.17.0", registry = "sw-ngc-forge-cargo-local" }
hyper = { version = "0.14.27", features=["full"]}
http = { version = "0.2.9" }
opentelemetry = { version = "0.21.0", features = ["logs"] }
opentelemetry-semantic-conventions = "0.13.0"
opentelemetry-prometheus = "0.14.1"
opentelemetry-otlp = { version = "0.14.0", features = ["logs"] }
opentelemetry_sdk = { version = "0.21.1", features = ["logs", "rt-tokio"] }
prometheus = "*"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "*"
tracing = "*"
thiserror = "1"
tokio = { workspace = true }
tonic = { workspace = true }

# [local-dependencies]
rpc = { path = "../rpc" }
forge-tls = { path = "../common/tls" }
forge-version = { path = "../common/version" }

[build-dependencies]
forge-version = { path = "../common/version" }
