[package]
name = "dhcp"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
derive_builder = "*"
ipnetwork = "*"
libc = "*"
log = "*"
mac_address = "*"
once_cell = "*"
rpc = { path = "../rpc" }
tokio = { version = "*", features = ["rt"] }
tonic = "0.8.0"
uuid = "1.0"

[build-dependencies]
cbindgen = "*"
cc = "1.0"
