[package]
name = "dhcp"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "*"
rpc = { path = "../rpc" }
uuid = "*"
tokio = { version = "*", features = ["rt"] }
tonic = "*"
once_cell = "*"
mac_address = "*"
log = "*"
derive_builder = "*"

[build-dependencies]
cc = "1.0"
cbindgen = "*"
