[package]
name = "dhcp"
version = "0.0.1"
edition.workspace = true
license-file = "LICENSE"
authors = ["NVIDIA Forge Engineering <swngc-forge-dev@exchange.nvidia.com>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
derive_builder = "*"
hyper = "*"
ipnetwork = "*"
lazy_static = "1.4.0"
libc = "*"
log = "*"
lru = "0.8.1"
mac_address = "*"
once_cell = "*"
prost = "0.11.3"
rpc = { path = "../rpc" }
tokio = { workspace = true }
tonic = "0.8.0"
uuid = "1.0"

[dev-dependencies]
anyhow = "1.0.66"
dhcproto = "0.8.0"
serde_json = "1.0.89"

[build-dependencies]
cbindgen = "*"
cc = "1.0"
