[package]
name = "dhcp"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "*"
eui48 = "0.4.0"
rpc = { path = "../rpc" }

[build-dependencies]
cc = "1.0"
cbindgen = "*"
