[package]
name = "dhcp"
version = "0.0.1"
edition.workspace = true
license-file = "LICENSE"
authors = ["NVIDIA Forge Engineering <swngc-forge-dev@exchange.nvidia.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
derive_builder = "*"
ipnetwork = "*"
libc = "*"
log = "*"
mac_address = "*"
once_cell = "*"
rpc = { path = "../rpc" }
tokio = { workspace = true }
tonic = "0.8.0"
uuid = "1.0"

[build-dependencies]
cbindgen = "*"
cc = "1.0"
