apiVersion: v1
kind: ConfigMap
metadata:
  name: carbide-pxe-configuration
  namespace: default
data:
  Rocket.toml: |
    [default]
    address = "0.0.0.0"
    carbide_api_url = "http://carbide-api:1079"
    port = 8000
    
    [development]
    template_dir = "/opt/carbide/pxe/templates"
    
    [production]
    template_dir = "/opt/carbide/pxe/templates"
