apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: carbide-pxe
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: carbide-pxe-config
    behavior:  create
    files:
    - Rocket.toml=rocket.toml
