[default]
address = "0.0.0.0"
carbide_api_url = "http://carbide-api:1079"
port = 8000

[development]
template_dir = "/opt/carbide/pxe/templates/"
address = "0.0.0.0"
port = 8000

[production]
template_dir = "/opt/carbide/pxe/templates/"
