[package]
name = "systest"
version = "0.1.0"
authors = ["Vishnu Rangayyan <vrangayyan@nvidia.com>"]

[dependencies]
ipmiconsole-sys = { path = "..", default-features = false, features = ["libc"] }
getopts = "0.2.21"
libc = { version = "0.2", optional = true }
termios = "0.3.3"
errno = "0.2.8"

[build-dependencies]

[features]
default = ["libc"]
