apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbide-api-deployment
  labels:
    app: carbide-api
spec:
  selector:
    matchLabels:
      app: carbide-api
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: carbide-api
    spec:
      containers:
        - name: carbide-api
          image: carbide:latest
          imagePullPolicy:  IfNotPresent
          command: ["/bin/sh", "-c", "/opt/carbide/carbide-api run --datastore=\"${CARBIDE_API_DATASTORE}\" --listen=\"127.0.0.1:1079\" --bootstrap_listen=\"127.0.0.1:1078\""]
          ports:
          - containerPort: 1079
            name: carbide-http
        - name: envoy
          image: envoyproxy/envoy-dev:35f8d59b1172a85f02dd119791a9ef42c728cfa8
          envFrom:
          - configMapRef:
              name: envoy-carbide-api-config
          imagePullPolicy:  IfNotPresent
          ports:
          - containerPort: 11079
            name: api-envoy
