apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:

namespace: kube-system

images:
  - name: carbide:latest
    newName: quay.io/nvmetal/carbide
    newTag: 0.0.1
