apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "common.names.fullname" . }}-certificate
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  duration: 720h
  renewBefore: 360h
  dnsNames:
    - bmc-mock.{{ include "common.names.namespace" . }}.svc.{{ .Values.clusterDomain }}
  uris:
    - spiffe://{{.Values.trustDomain}}/{{ include "common.names.namespace" . }}/sa/bmc-mock
  privateKey:
    algorithm: ECDSA
    size: 384
  issuerRef:
    kind: ClusterIssuer
    name: vault-forge-issuer
    group: cert-manager.io
  secretName: {{ template "common.names.fullname" . }}-certificate
