[package]
name = "carbide-tls"
version = "0.0.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

# TODO: rename to carbide_tls in source
[lib]
name = "forge_tls"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tonic = { workspace = true }
thiserror = "2.0.3"

[lints]
workspace = true
