[package]
name = "forge-tls"
version = "0.1.0"
edition.workspace = true
license = "LicenseRef-NvidiaProprietary"
authors = ["NVIDIA Forge Engineering <swngc-forge-dev@exchange.nvidia.com>"]


[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tonic = { workspace = true }
thiserror = "1.0.44"

 # [local-dependencies]
rpc = { path = "../../rpc" }

