[default]
address = "0.0.0.0"
carbide_api_url = "http://10.150.51.235:22079"
carbide_pxe_url = "http://10.150.51.235:8080"
carbide_ntp_server = "10.149.10.130"
port = 8000

[development]
template_dir = "/opt/carbide/pxe/templates"

[production]
template_dir = "/opt/carbide/pxe/templates"
