[package]
name = "carbide-mockdpa"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "mockdpa"
path = "src/main.rs"

[dependencies]
chrono = { features = ["serde"] , workspace = true }
clap = { features = ["derive"] , workspace = true }
rumqttc = { workspace = true }
serde = { features = ["derive"] , workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
prost = { workspace = true }
tokio = { features = ["full"] , workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
mqttea = { path = "../mqttea" }
carbide-rpc = { path = "../rpc" }

[build-dependencies]
prost-build = "0.14"
