[package]
name = "carbide-dns"
version = "0.0.1"
description = "Carbide is bare metal provisioning system with auto-discovery and API based machine manipulation"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[[bin]]
name = "carbide-dns"
path = "src/main.rs"

[dependencies]
async-trait = { workspace = true }
clap = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { features = [
  "env-filter",
  "local-time",
], workspace = true }
trust-dns-server = { workspace = true }
trust-dns-resolver = { workspace = true }

# [local-dependencies]
carbide-tls = { path = "../tls" }
carbide-version = { path = "../version" }
carbide-rpc = { path = "../rpc" }

[build-dependencies]
carbide-version = { path = "../version" }

[lints]
workspace = true
