---
- - :permit
  - MIT
  - :who: NGC DevOps
    :why: Included in the automatic approvals listed in https://confluence.nvidia.com/display/LEG/Open+Source+Software+Requests
    :versions: []
    :when: 2021-06-04 12:27:56.175691000 Z
- - :permit
  - Apache 2.0
  - :who: NGC DevOps
    :why: Included in the automatic approvals listed in https://confluence.nvidia.com/display/LEG/Open+Source+Software+Requests
    :versions: []
    :when: 2021-06-04 12:27:56.175691000 Z
- - :permit
  - BSD-3-Clause
  - :who: NGC DevOps
    :why: Included in the automatic approvals listed in https://confluence.nvidia.com/display/LEG/Open+Source+Software+Requests
    :versions: []
    :when: 2021-06-04 12:27:56.175691000 Z
- - :permit
  - BSD Zero Clause License
  - :who: NGC DevOps
    :why: Included in the automatic approvals listed in https://confluence.nvidia.com/display/LEG/Open+Source+Software+Requests
    :versions: []
    :when: 2021-06-04 12:27:56.175691000 Z
- - :permit
  - Simplified BSD
  - :who: NGC DevOps
    :why: Included in the automatic approvals listed in https://confluence.nvidia.com/display/LEG/Open+Source+Software+Requests
    :versions: []
    :when: 2021-06-04 12:27:56.175691000 Z
- - :permit
  - CC0-1.0
  - :who: NGC DevOps
    :why: Included in the automatic approvals listed in https://confluence.nvidia.com/display/LEG/Open+Source+Software+Requests
    :versions: []
    :when: 2021-06-04 12:27:56.175691000 Z
- - :permit
  - CC0-BY-4.0
  - :who: NGC DevOps
    :why: Included in the automatic approvals listed in https://confluence.nvidia.com/display/LEG/Open+Source+Software+Requests
    :versions: []
    :when: 2021-06-04 12:27:56.175691000 Z
