[package]
name = "carbide-mlxconfig-registry"
version = "0.0.0"
edition = "2021"
description = "Compile-time Mellanox hardware configuration registry."

[lib]
name = "mlxconfig_registry"

[dependencies]
once_cell = "1.19"
carbide-mlxconfig-device = { path = "../device" }
carbide-mlxconfig-variables = { path = "../variables" }

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
carbide-mlxconfig-device = { path = "../device" }
carbide-mlxconfig-variables = { path = "../variables" }
