[package]
name = "machine-a-tron"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive", "env"] }
lazy_static = "1.4.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
uuid = { version = "1.6.1", features = ["v4"] }
serde = "1.0.195"
serde_json = "1.0.111"
tokio = { workspace = true }
tonic = { workspace = true }
socket2 = "0.5.5"
base64 = "0.22.1"
chrono = "0.4.34"
thiserror = "2"
axum = "0.7.5"
crossterm = { version = "0.28.1", features = ["event-stream"] }
ratatui = "0.29.0"
dhcproto = "0.12.0"
mac_address = "1.1.5"
futures = "0.3.30"
figment = { version = "0.10.16", features = ["toml"] }
libredfish = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream", "socks", "multipart"] }
eyre = "0.6.12"
tower = "0.5.1"
http-body = "1.0.0"
regex = "1.10.5"
bytes = "1.6.0"
tempfile = "3"
duration-str = "0.11"
rand = "0.8"

# [local-dependencies]
rpc = { path = "../../rpc" }
bmc-mock = { path = "../bmc-mock" }
forge-tls = { path = "../../common/tls" }
utils = { path = "../../common/utils" }
rcgen = "0.13.1"
