[package]
name = "forge-version"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[dependencies]
# Nothing should be here. The crate needs to be very lightweight
# since its used as a dependency for everything else.
