[package]
name = "carbide-machine-validation"
version = "0.0.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[lib]
name = "machine_validation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

carbide-uuid = { path = "../uuid" }

tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = { version = "2", registry = "cratesio" }
futures = { version = "0.3", default-features = false }
carbide-tls = { path = "../tls" }
carbide-rpc = { path = "../../rpc" }
carbide-utils = { path = "../../common/utils" }
tonic = { workspace = true }
chrono = { version = "0.4.34", features = ["serde"] }
tracing = "0.1.40"
reqwest = { version = "*", default-features = false, features = [
    "rustls-tls",
    "stream",
] }
futures-util = "0.3"

[lints]
workspace = true
