[package]
name = "machine-validation"
version = "0.1.0"
edition.workspace = true
license = "LicenseRef-NvidiaProprietary"
authors = ["NVIDIA Forge Engineering <swngc-forge-dev@exchange.nvidia.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = { version = "2", registry = "cratesio" }
futures = { version = "0.3", default-features = false }
forge-tls = { path = "../tls" }
rpc = { path = "../../rpc" }
utils = { path = "../../common/utils" }
tonic = { workspace = true }
chrono = { version = "0.4.34", features = ["serde"] }
tracing = "0.1.40"
reqwest = { version = "*", default-features = false, features = [
    "rustls-tls",
    "stream",
] }
futures-util = "0.3"

[lints]
workspace = true