[package]
name = "machine-validation"
version = "0.1.0"
edition.workspace = true
license = "LicenseRef-NvidiaProprietary"
authors = ["NVIDIA Forge Engineering <swngc-forge-dev@exchange.nvidia.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive", "env"] }
prettytable-rs = "^0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9.25"
regex = "1.6"
colored = "2.0"
rayon = "1.5"
thiserror = { version = "1", registry = "cratesio" }
anyhow = { version = "1", registry = "cratesio" }
async-trait = "*"
futures = { version = "0.3", default-features = false }
forge-tls = { path = "../tls" }
rpc = { path = "../../rpc" }
tonic = { workspace = true }
chrono = { version = "0.4.34", features = ["serde"] }
tracing = "0.1.40"
