[package]
name = "freeipmi-sys"
version = "1.6.9"
edition = "2021"
authors = ["Vishnu Rangayyan <vrangayyan@nvidia.com"]
links = "freeipmi"
build = "build.rs"
description = """
Bindings to libfreeipmi for ipmi commands to out-of-band (ipmi over lan) and inband (kcs, etc) BMCs
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "freeipmi_sys"
path = "src/lib.rs"

[dependencies]
libc = { version = "0.2", optional = true }
thiserror = "1.0"
num_enum = "0.5.7"
serde = {version = "1.0", features = ["derive"] }

[build-dependencies]
pkg-config = "0.3.25"
cc = "1.0"

[features]
default = ["libc"]
static = []
