# permissions for end users to edit leafs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: leaf-editor-role
rules:
- apiGroups:
  - networkfabric.vpc.forge.gitlab-master.nvidia.com
  resources:
  - leafs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networkfabric.vpc.forge.gitlab-master.nvidia.com
  resources:
  - leafs/status
  verbs:
  - get
