# permissions for end users to view leafs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: leaf-viewer-role
rules:
- apiGroups:
  - networkfabric.vpc.forge.gitlab-master.nvidia.com
  resources:
  - leafs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networkfabric.vpc.forge.gitlab-master.nvidia.com
  resources:
  - leafs/status
  verbs:
  - get
