# permissions for end users to view networkpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkpolicy-viewer-role
rules:
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - networkpolicies/status
  verbs:
  - get
