# permissions for end users to view resourcegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcegroup-viewer-role
rules:
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - resourcegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - resourcegroups/status
  verbs:
  - get
