
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - networkfabric.vpc.forge.gitlab-master.nvidia.com
  resources:
  - configurationresourcepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networkfabric.vpc.forge.gitlab-master.nvidia.com
  resources:
  - configurationresourcepools/finalizers
  verbs:
  - update
- apiGroups:
  - networkfabric.vpc.forge.gitlab-master.nvidia.com
  resources:
  - configurationresourcepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networkfabric.vpc.forge.gitlab-master.nvidia.com
  resources:
  - leafs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networkfabric.vpc.forge.gitlab-master.nvidia.com
  resources:
  - leafs/finalizers
  verbs:
  - update
- apiGroups:
  - networkfabric.vpc.forge.gitlab-master.nvidia.com
  resources:
  - leafs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - managedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - managedresources/finalizers
  verbs:
  - update
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - managedresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - networkpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - networkpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - resourcegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - resourcegroups/finalizers
  verbs:
  - update
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - resourcegroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - sharedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - sharedresources/finalizers
  verbs:
  - update
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - sharedresources/status
  verbs:
  - get
  - patch
  - update
