# permissions for end users to edit sharedresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sharedresource-editor-role
rules:
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - sharedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.vpc.forge.gitlab-master.nvidia.com
  resources:
  - sharedresources/status
  verbs:
  - get
