
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-networkfabric-vpc-forge-gitlab-master-nvidia-com-v1alpha1-configurationresourcepool
  failurePolicy: Fail
  name: mconfigurationresourcepool.kb.io
  rules:
  - apiGroups:
    - networkfabric.vpc.forge.gitlab-master.nvidia.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - configurationresourcepools
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-networkfabric-vpc-forge-gitlab-master-nvidia-com-v1alpha1-leaf
  failurePolicy: Fail
  name: mleaf.kb.io
  rules:
  - apiGroups:
    - networkfabric.vpc.forge.gitlab-master.nvidia.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - leafs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-resource-vpc-forge-gitlab-master-nvidia-com-v1alpha1-managedresource
  failurePolicy: Fail
  name: mmanagedresource.kb.io
  rules:
  - apiGroups:
    - resource.vpc.forge.gitlab-master.nvidia.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedresources
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-resource-vpc-forge-gitlab-master-nvidia-com-v1alpha1-networkpolicy
  failurePolicy: Fail
  name: mnetworkpolicy.kb.io
  rules:
  - apiGroups:
    - resource.vpc.forge.gitlab-master.nvidia.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networkpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-resource-vpc-forge-gitlab-master-nvidia-com-v1alpha1-resourcegroup
  failurePolicy: Fail
  name: mresourcegroup.kb.io
  rules:
  - apiGroups:
    - resource.vpc.forge.gitlab-master.nvidia.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - resourcegroups
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networkfabric-vpc-forge-gitlab-master-nvidia-com-v1alpha1-configurationresourcepool
  failurePolicy: Fail
  name: vconfigurationresourcepool.kb.io
  rules:
  - apiGroups:
    - networkfabric.vpc.forge.gitlab-master.nvidia.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - configurationresourcepools
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networkfabric-vpc-forge-gitlab-master-nvidia-com-v1alpha1-leaf
  failurePolicy: Fail
  name: vleaf.kb.io
  rules:
  - apiGroups:
    - networkfabric.vpc.forge.gitlab-master.nvidia.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - leafs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-resource-vpc-forge-gitlab-master-nvidia-com-v1alpha1-managedresource
  failurePolicy: Fail
  name: vmanagedresource.kb.io
  rules:
  - apiGroups:
    - resource.vpc.forge.gitlab-master.nvidia.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedresources
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-resource-vpc-forge-gitlab-master-nvidia-com-v1alpha1-networkpolicy
  failurePolicy: Fail
  name: vnetworkpolicy.kb.io
  rules:
  - apiGroups:
    - resource.vpc.forge.gitlab-master.nvidia.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networkpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-resource-vpc-forge-gitlab-master-nvidia-com-v1alpha1-resourcegroup
  failurePolicy: Fail
  name: vresourcegroup.kb.io
  rules:
  - apiGroups:
    - resource.vpc.forge.gitlab-master.nvidia.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - resourcegroups
  sideEffects: None
