[package]
name = "carbide-utils"
version = "0.0.0"
edition.workspace = true
license-file.workspace = true
authors.workspace = true

# TODO: rename to carbide_utils in source
[lib]
name = "utils"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
sqlx = ["carbide-network/sqlx", "dep:sqlx"]

[dependencies]
byte-unit = "5.1.6"
chrono = "0.4.34"
clap = { workspace = true }
eyre = "*"
prettytable-rs = { version = "0.10", default-features = false, features = ["csv"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9.25"
thiserror = "2.0.3"
tracing = "*"
tokio = { workspace = true }
ipnetwork = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "mac_address", "ipnetwork", "uuid", "migrate", "postgres", "chrono", "macros", "json"], optional = true }
tonic = { workspace = true }
humantime = "2.1.0"

# [local-dependencies]
config-version = { path = "../config-version" }
carbide-health-report = { path = "../health-report" }
carbide-network = { path = "../network" }
carbide-uuid = { path = "../../common/uuid" }
carbide-rpc = { path = "../../rpc" }

[lints]
workspace = true
