apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "common.names.fullname" . }}-db-migrations
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: carbide-api
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-1"
  {{- else }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-1"
  {{- end }}
spec:
  template:
    metadata:
      {{- if .Values.container.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.container.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: carbide-api
        {{- if .Values.container.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.container.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      {{- include "container.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.container.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.container.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.container.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.container.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.container.podAffinityPreset "component" "carbide-api" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.container.podAntiAffinityPreset "component" "carbide-api" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.container.nodeAffinityPreset.type "key" .Values.container.nodeAffinityPreset.key "values" .Values.container.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.container.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.container.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.container.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.container.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.container.priorityClassName }}
      priorityClassName: {{ .Values.container.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.container.schedulerName }}
      schedulerName: {{ .Values.container.schedulerName | quote }}
      {{- end }}
      {{- if .Values.container.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.container.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.container.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.container.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.container.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.container.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        {{- if and .Values.volumePermissions.enabled .Values.persistence.enabled }}
        - name: volume-permissions
          image: {{ include "container.volumePermissions.image" . }}
          imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy | quote }}
          command:
            - /sbin/foo-bare
          securityContext: {{- include "common.tplvalues.render" (dict "value" .Values.volumePermissions.containerSecurityContext "context" $) | nindent 12 }}
          {{- if .Values.volumePermissions.resources }}
          resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: persistence
              mountPath: {{ .Values.persistence.mountPath }}
              {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
              {{- end }}
        {{- end }}
        {{- if .Values.container.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.container.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - command:
            - /bin/sh
            - -c
            - /opt/carbide/carbide-api migrate --datastore="postgres://${DATASTORE_USER}:${DATASTORE_PASSWORD}@${DATASTORE_HOST}:${DATASTORE_PORT}/${DATASTORE_NAME}"
            #- sleep 600
          env:
            - name: DATASTORE_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ tpl .Values.postgresSecretRef . }}
            - name: DATASTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ tpl .Values.postgresSecretRef . }}
            - name: DATASTORE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ tpl .Values.postgresConfigMapName . }}
                  key: DB_HOST
            - name: DATASTORE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ tpl .Values.postgresConfigMapName . }}
                  key: DB_PORT
            - name: DATASTORE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ tpl .Values.postgresConfigMapName . }}
                  key: DB_NAME
          image: {{ template "container.image" . }}
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          name: carbide-db-migrations
      restartPolicy: OnFailure
