apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-metrics" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: carbide-api
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.metricsService.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.metricsService.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.metricsService.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.metricsService.type }}
  {{- if and .Values.metricsService.clusterIP (eq .Values.service.type "ClusterIP") }}
  clusterIP: {{ .Values.metricsService.clusterIP }}
  {{- end }}
  {{- if .Values.metricsService.sessionAffinity }}
  sessionAffinity: {{ .Values.metricsService.sessionAffinity }}
  {{- end }}
  {{- if .Values.metricsService.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.metricsService.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.metricsService.type "LoadBalancer") (eq .Values.metricsService.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.metricsService.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.metricsService.type "LoadBalancer") (not (empty .Values.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.metricsService.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.metricsService.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.metricsService.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.metricsService.ports.http }}
      targetPort: {{ .Values.metricsService.targetPorts.http }}
      protocol: TCP
      {{- if and (or (eq .Values.metricsService.type "NodePort") (eq .Values.metricsService.type "LoadBalancer")) (not (empty .Values.metricsService.nodePorts.http)) }}
      nodePort: {{ .Values.metricsService.nodePorts.http }}
      {{- else if eq .Values.metricsService.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.metricsService.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.metricsService.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: carbide-api
