[book]
title = "Forge Documentation"
author = "Forge Development Team <forge-dev@exchange.nvidia.com>"

[rust]
edition = "2021"

[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]
[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
