[package]
name = "carbide-api"
version = "0.0.1"
edition = "2018"
description = "Carbide is a Bare Metal Provisioning system with auto-discovery and API based machine manipulation"
#readme = "README.md"

[lib]
name = "carbide"

[[bin]]
name = "carbide-api"
path = "src/main.rs"

[dependencies]
# protobufs/rpc interface
rpc = { path = "../rpc" }

# grpc
tonic = { version = "0.7.0", features = ["tls"] }
tonic-reflection = "0.4.0"

# http/service
http = "0.2"
tower = "0.4"
tower-layer = "0.3"
tower-http = { version = "0.3", features = ["auth"] }

# authentication
jsonwebtoken = { version = "8.1", default-features = false }

# databases
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "mac_address", "ipnetwork", "uuid", "migrate", "postgres", "chrono", "macros", "json" ] }
sqlxmq = { version = "0.3.4", default-features = false, features = [ "runtime-tokio-rustls"]}


# async
tokio = { version = "1.9", features = ["full"] }
log = { version = "*", features = ["serde"] }
pretty_env_logger = "*"
color-eyre = "0.5.11"
serde = {version = "1.0", features = ["derive"] }
serde_json = "*"
tokio-stream = "*"
futures = "0.3"

# data types
uuid = { version = "0.8.2", features = ["v4", "serde"] }
ipnetwork = { version = "^0.17.0", features = ["serde"] }
patricia_tree = "^0"
mac_address = "1.1.2"
chrono = "0.4.19"

# misc
itertools = "*"
thiserror = "1.0"
async-trait = "*"
rust-fsm = "0.6.0"
freeipmi-sys = { path="../ipmi/freeipmi-sys" }

# cli
clap = { version = "~3", features = ["derive"] }

kube = { version = "0.72.0", features = ["runtime", "derive", "client"] }
k8s-openapi = { version = "0.14.0", features = ["v1_23"] }
schemars = "*"

[build-dependencies]
tonic-build = "0.7"

[dev-dependencies]
rand = "*"
rstest = "*"
