[package]
name = "carbide-api"
version = "0.0.1"
edition.workspace = true
description = "Carbide is a Bare Metal Provisioning system with auto-discovery and API based machine manipulation"
license = "LicenseRef-NvidiaProprietary"
authors = ["NVIDIA Forge Engineering <swngc-forge-dev@exchange.nvidia.com>"]

[lib]
name = "carbide"

[[bin]]
name = "carbide-api"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.65"
async-trait = "*"
base64 = "0.13"
casbin = "2.0"
chrono = "0.4.19"
clap = { version = "~3", features = ["derive", "env"] }
color-eyre = "0.5.11"
data-encoding = "2.3.3"
futures = "0.3"
futures-util = "0.3"
http = "0.2"
hyper = "0.14"
ipnetwork = { version = "^0.19.0", features = ["serde"] }
itertools = "*"
jsonwebtoken = { version = "8.1", default-features = false }
k8s-openapi = { version = "0.14.0", features = ["v1_23"] }
kube = { version = "0.72.0", features = ["runtime", "derive", "client"] }
libredfish = { version = "0.6.0", registry = "sw-ngc-forge-cargo-local" }
log = { version = "*", features = ["serde"] }
mac_address = "1.1.2"
once_cell = "1.13.1"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
opentelemetry-semantic-conventions = "0.10.0"
opentelemetry-prometheus = "0.11"
patricia_tree = "^0"
pretty_env_logger = "*"
prometheus = "0.13"
rand = "0.8"
rust-fsm = "0.6.0"
schemars = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
sha2 = "0.10.3"
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "mac_address", "ipnetwork", "uuid", "migrate", "postgres", "chrono", "macros", "json"] }
sqlxmq = { version = "0.4", default-features = false, features = ["runtime-tokio-rustls"] }
thiserror = "1.0"
tokio = { workspace = true }
tokio-rustls = "0.23"
rustls-pemfile = "1.0"
spiffe = "0.2"
tokio-stream = "*"
tonic = { version = "0.8.0", features = ["tls"] }
tonic-reflection = "0.5.0"
tower = "0.4"
tower-http = { version = "0.3", features = ["add-extension", "auth"] }
tower-layer = "0.3"
tracing = "*"
tracing-opentelemetry = "0.18.0"
tracing-subscriber = { version = "*", features = ["env-filter", "local-time"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
vaultrs = "0.6.2"
x509-parser = { version = "0.14", features = ["verify"] }

#only local dependencies here please
forge_credentials = { path = "../forge_credentials" }
rpc = { path = "../rpc" }

[build-dependencies]
tonic-build = "0.8"

[dev-dependencies]
rstest = "0.13.0"
rstest_reuse = "0.4.0"
ctor = "0.1"
lazy_static = "1.4.0"

[features]
kubernetes = []
