[package]
name = "carbide-api"
version = "0.0.1"
edition.workspace = true
description = "Carbide is a Bare Metal Provisioning system with auto-discovery and API based machine manipulation"
license = "LicenseRef-NvidiaProprietary"
authors = ["NVIDIA Forge Engineering <swngc-forge-dev@exchange.nvidia.com>"]

[lib]
name = "carbide"

[[bin]]
name = "carbide-api"
path = "src/main.rs"

[dependencies]
arc-swap = "1.6"
askama = "0.12.1"
askama_escape = "0.10"
async-trait = "*"
axum = { version = "0.6.18", features = ["http2"] }
base64 = "0.21.5"
casbin = { version = "2.0", features = ["glob"] }
chrono = "0.4.19"
clap = { workspace = true }
console-subscriber = { git = "https://github.com/grahamking/console.git", branch = "main" }
data-encoding = "2.3.3"
eyre = "*"
figment = { version = "0.10.10", features = ["env", "toml"] }
futures = "0.3"
futures-util = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
hyper-rustls = "0.24"
hyper-timeout = "0.4"
ipnetwork = { version = "^0.20.0", features = ["serde"] }
itertools = "*"
jsonwebtoken = { version = "8.1", default-features = false }
libredfish = { version = "0.16.0", registry = "sw-ngc-forge-cargo-local" }
mac_address = "1.1.2"
num_cpus = "1.16.0"
once_cell = "1.13.1"
opentelemetry = { version = "0.21", features = ["logs"] }
opentelemetry-semantic-conventions = "0.13.0"
opentelemetry-prometheus = "0.14.1"
opentelemetry-otlp = { version = "0.14.0", features = ["logs"] }
opentelemetry_sdk = { version = "0.21.1", features = ["logs", "rt-tokio"] }
toml = "0.8.8"
patricia_tree = "^0"
prometheus = "0.13"
rand = "0.8"
regex = "1.6"
schemars = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
sha2 = "0.10.3"
sqlx = { version = "0.7.1", features = [
    "runtime-tokio-rustls",
    "mac_address",
    "ipnetwork",
    "uuid",
    "migrate",
    "postgres",
    "chrono",
    "macros",
    "json",
] }
thiserror = "1.0"
tokio = { workspace = true }
tokio-rustls = "0.24"
rustls-pemfile = "1.0"
tokio-stream = "*"
tonic = { workspace = true }
tonic-reflection = "0.10"
url = { version = "2", features = ["serde"] }
tower = "0.4"
tower-http = { version = "0.4", features = [
    "add-extension",
    "auth",
    "normalize-path",
] }
tower-layer = "0.3"
tracing = "*"
tracing-opentelemetry = "0.22.0"
tracing-subscriber = { version = "*", features = ["env-filter", "local-time"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
vaultrs = "0.7"
version-compare = "0.1.1"
x509-parser = { version = "0.15.1", features = ["verify"] }

#only local dependencies here please
forge_secrets = { path = "../forge_secrets" }
forge-version = { path = "../version" }
rpc = { path = "../rpc" }
utils = { path = "../utils" }

[build-dependencies]
tonic-build = "0.10.2"
forge-version = { path = "../version" }

[dev-dependencies]
figment = { version = "0.10.10", features = ["env", "test", "toml"] }
ctor = "0.1"
lazy_static = "1.4.0"
