[package]
name = "carbide-api"
version = "0.0.1"
edition = "2018"
description = "Carbide is a Bare Metal Provisioning system with auto-discovery and API based machine manipulation"
#readme = "README.md"

[lib]
name = "carbide"

[[bin]]
name = "carbide-api"
path = "src/main.rs"

[dependencies]
# protobufs/rpc interface
rpc = { path = "../rpc" }

# grpc
tonic = { version = "0.5", features = ["tls"] }
tonic-reflection = "0.2"

# databases
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "mac_address", "ipnetwork", "uuid", "migrate", "postgres", "chrono", "macros" ] }

# async
tokio = { version = "1.9", features = ["full"] }
clap = "3.0.0-beta.2"
log = { version = "*", features = ["serde"] }
pretty_env_logger = "*"
color-eyre = "0.5.11"
serde = {version = "1.0", features = ["derive"] }
tokio-stream = "*"
futures = "0.3"

# data types
uuid = { version = "0.8", features = ["v4", "serde"] }
ipnetwork = { version = "^0.17.0", features = ["serde"] }
patricia_tree = "^0"
mac_address = "1.1.2"
chrono = "0.4.19"

# misc
itertools = "*"
thiserror = "1.0"

[build-dependencies]
tonic-build = "0.5"

[dev-dependencies]
rand = "*"
rstest = "*"
