[package]
name = "carbide-api"
version = "0.0.1"
edition = "2021"
description = "Carbide is a Bare Metal Provisioning system with auto-discovery and API based machine manipulation"
#readme = "README.md"

[lib]
name = "carbide"

[[bin]]
name = "carbide-api"
path = "src/main.rs"

[dependencies]
async-trait = "*"
chrono = "0.4.19"
clap = { version = "~3", features = ["derive"] }
color-eyre = "0.5.11"
freeipmi-sys = { path="../ipmi/freeipmi-sys" }
futures = "0.3"
http = "0.2"
ipnetwork = { version = "^0.19.0", features = ["serde"] }
itertools = "*"
jsonwebtoken = { version = "8.1", default-features = false }
k8s-openapi = { version = "0.14.0", features = ["v1_23"] }
kube = { version = "0.72.0", features = ["runtime", "derive", "client"] }
log = { version = "*", features = ["serde"] }
lru = "0.8"
mac_address = "1.1.2"
once_cell = "1.13.1"
patricia_tree = "^0"
pretty_env_logger = "*"
rpc = { path = "../rpc" }
rust-fsm = "0.6.0"
schemars = "*"
serde = {version = "1.0", features = ["derive"] }
serde_json = "*"
sqlx = { version = "0.6", features = [ "runtime-tokio-rustls", "mac_address", "ipnetwork", "uuid", "migrate", "postgres", "chrono", "macros", "json" ] }
sqlxmq = { version = "0.4", default-features = false, features = [ "runtime-tokio-rustls"]}
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-stream = "*"
tonic = { version = "0.8.0", features = ["tls"] }
tonic-reflection = "0.5.0"
tower = "0.4"
tower-http = { version = "0.3", features = ["auth"] }
tower-layer = "0.3"
tracing = "*"
tracing-subscriber = { version = "*", features = [ "env-filter", "local-time"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

[build-dependencies]
tonic-build = "0.8"

[dev-dependencies]
rand = "0.8"
rstest = "0.13.0"
ctor = "0.1"

[features]
kubernetes = []
