apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ./base/carbide-api
  - ./base/carbide-dhcp
  - ./base/carbide-pxe
  - ./base/carbide-dns
  - ./base/postgres
  - ./base/envoy
  - ./base/carbide-relay
