[package]
name = "forge-network"
version = "0.0.1"
edition.workspace = true
description = "Common networking code for Forge components."
license-file.workspace = true
authors.workspace = true

[dependencies]
eyre = "*"
ipnetwork = { version = "^0.20.0", features = ["serde"] }
mac_address = "1.1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
sqlx = { version = "0.7.1", features = [
    "runtime-tokio-rustls",
    "mac_address",
    "ipnetwork",
    "uuid",
    "migrate",
    "postgres",
    "chrono",
    "macros",
    "json",
] }

rpc = { path = "../../rpc" }